"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from emailr.errors import EmailrError
from emailr.types import BaseModel, OptionalNullable, UNSET
import httpx
from typing import Any, Optional


class ErrorData(BaseModel):
    error: str
    code: Optional[str] = None
    details: OptionalNullable[Any] = UNSET


@dataclass(unsafe_hash=True)
class Error(EmailrError):
    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
