"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from emailr.errors import EmailrError
from emailr.types import BaseModel
import httpx
from typing import Optional


class PostV1UnsubscribeNotFoundErrorData(BaseModel):
    error: str


@dataclass(unsafe_hash=True)
class PostV1UnsubscribeNotFoundError(EmailrError):
    r"""Contact not found"""

    data: PostV1UnsubscribeNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV1UnsubscribeNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
