"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from emailr.errors import EmailrError
from emailr.types import BaseModel
import httpx
from typing import Optional


class PutV1TopicsIDNotFoundErrorData(BaseModel):
    error: str


@dataclass(unsafe_hash=True)
class PutV1TopicsIDNotFoundError(EmailrError):
    r"""Topic not found"""

    data: PutV1TopicsIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV1TopicsIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV1TopicsIDUnauthorizedErrorData(BaseModel):
    error: str


@dataclass(unsafe_hash=True)
class PutV1TopicsIDUnauthorizedError(EmailrError):
    r"""Unauthorized"""

    data: PutV1TopicsIDUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV1TopicsIDUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
