"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .addcontacttosegmentop import (
        AddContactToSegmentRequest,
        AddContactToSegmentRequestTypedDict,
    )
    from .adddomainrequest import AddDomainRequest, AddDomainRequestTypedDict
    from .apikey import APIKey, APIKeyTypedDict
    from .apikeylistitem import APIKeyListItem, APIKeyListItemTypedDict
    from .attachment import Attachment, AttachmentTypedDict
    from .broadcast import Broadcast, BroadcastTypedDict
    from .bulkcreatecontactsrequest import (
        BulkCreateContactsRequest,
        BulkCreateContactsRequestTypedDict,
    )
    from .bulkcreatecontactsresponse import (
        BulkCreateContactsResponse,
        BulkCreateContactsResponseTypedDict,
    )
    from .contact import Contact, ContactTypedDict
    from .contactlistresponse import ContactListResponse, ContactListResponseTypedDict
    from .createapikeyrequest import CreateAPIKeyRequest, CreateAPIKeyRequestTypedDict
    from .createbroadcastrequest import (
        CreateBroadcastRequest,
        CreateBroadcastRequestTypedDict,
    )
    from .createcontactrequest import (
        CreateContactRequest,
        CreateContactRequestTypedDict,
    )
    from .createsegmentrequest import (
        CreateSegmentRequest,
        CreateSegmentRequestTypedDict,
    )
    from .createtemplaterequest import (
        CreateTemplateRequest,
        CreateTemplateRequestTypedDict,
    )
    from .createwebhookrequest import (
        CreateWebhookRequest,
        CreateWebhookRequestTypedDict,
    )
    from .delete_v1_contact_sync_id_op import (
        DeleteV1ContactSyncIDRequest,
        DeleteV1ContactSyncIDRequestTypedDict,
        DeleteV1ContactSyncIDResponse,
        DeleteV1ContactSyncIDResponseTypedDict,
    )
    from .delete_v1_integrations_id_op import (
        DeleteV1IntegrationsIDRequest,
        DeleteV1IntegrationsIDRequestTypedDict,
        DeleteV1IntegrationsIDResponse,
        DeleteV1IntegrationsIDResponseTypedDict,
    )
    from .delete_v1_topics_id_op import (
        DeleteV1TopicsIDRequest,
        DeleteV1TopicsIDRequestTypedDict,
        DeleteV1TopicsIDResponse,
        DeleteV1TopicsIDResponseTypedDict,
    )
    from .deletecontactop import DeleteContactRequest, DeleteContactRequestTypedDict
    from .deletedomainop import DeleteDomainRequest, DeleteDomainRequestTypedDict
    from .deletetemplateop import DeleteTemplateRequest, DeleteTemplateRequestTypedDict
    from .deletewebhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .dnsrecord import DNSRecord, DNSRecordTypedDict, Type
    from .dnsverificationstatus import (
        DNSVerificationStatus,
        DNSVerificationStatusTypedDict,
    )
    from .domain import Domain, DomainTypedDict
    from .domaindnsrecords import DomainDNSRecords, DomainDNSRecordsTypedDict
    from .domainverificationstatus import (
        DomainVerificationStatus,
        DomainVerificationStatusTypedDict,
    )
    from .email import Email, EmailTypedDict
    from .emailevent import EmailEvent, EmailEventTypedDict
    from .emailmetrics import EmailMetrics, EmailMetricsTypedDict
    from .get_v1_billing_usageop import (
        GetV1BillingUsageResponse,
        GetV1BillingUsageResponseTypedDict,
    )
    from .get_v1_contact_syncop import (
        GetV1ContactSyncResponse,
        GetV1ContactSyncResponseTypedDict,
        GetV1ContactSyncSourceType,
        Sync,
        SyncTypedDict,
    )
    from .get_v1_integrations_connectionsop import (
        Connection,
        ConnectionTypedDict,
        GetV1IntegrationsConnectionsResponse,
        GetV1IntegrationsConnectionsResponseTypedDict,
        Provider,
    )
    from .get_v1_integrations_supabase_callbackop import (
        GetV1IntegrationsSupabaseCallbackRequest,
        GetV1IntegrationsSupabaseCallbackRequestTypedDict,
    )
    from .get_v1_integrations_vercel_callbackop import (
        GetV1IntegrationsVercelCallbackRequest,
        GetV1IntegrationsVercelCallbackRequestTypedDict,
    )
    from .get_v1_topicsop import (
        GetV1TopicsResponse,
        GetV1TopicsResponseTypedDict,
        GetV1TopicsTopic,
        GetV1TopicsTopicTypedDict,
    )
    from .get_v1_unsubscribe_organizationid_op import (
        GetV1UnsubscribeOrganizationIDRequest,
        GetV1UnsubscribeOrganizationIDRequestTypedDict,
        GetV1UnsubscribeOrganizationIDResponse,
        GetV1UnsubscribeOrganizationIDResponseTypedDict,
        GetV1UnsubscribeOrganizationIDTopic,
        GetV1UnsubscribeOrganizationIDTopicTypedDict,
    )
    from .getbroadcastop import GetBroadcastRequest, GetBroadcastRequestTypedDict
    from .getcontactop import GetContactRequest, GetContactRequestTypedDict
    from .getdomaindnsstatusop import (
        GetDomainDNSStatusRequest,
        GetDomainDNSStatusRequestTypedDict,
    )
    from .getemailop import GetEmailRequest, GetEmailRequestTypedDict
    from .gettemplateop import GetTemplateRequest, GetTemplateRequestTypedDict
    from .getusageop import GetUsageRequest, GetUsageRequestTypedDict
    from .getwebhookdeliveriesop import (
        GetWebhookDeliveriesRequest,
        GetWebhookDeliveriesRequestTypedDict,
    )
    from .listcontactsop import ListContactsRequest, ListContactsRequestTypedDict
    from .listemailsop import (
        ListEmailsRequest,
        ListEmailsRequestTypedDict,
        ListEmailsResponse,
        ListEmailsResponseTypedDict,
        Pagination,
        PaginationTypedDict,
    )
    from .listlogsop import ListLogsRequest, ListLogsRequestTypedDict
    from .organization import Organization, OrganizationTypedDict
    from .post_v1_billing_checkoutop import (
        PlanType,
        PostV1BillingCheckoutRequest,
        PostV1BillingCheckoutRequestTypedDict,
        PostV1BillingCheckoutResponse,
        PostV1BillingCheckoutResponseTypedDict,
    )
    from .post_v1_billing_portalop import (
        PostV1BillingPortalResponse,
        PostV1BillingPortalResponseTypedDict,
    )
    from .post_v1_billing_webhooksop import (
        PostV1BillingWebhooksResponse,
        PostV1BillingWebhooksResponseTypedDict,
    )
    from .post_v1_contact_sync_supabaseop import (
        FieldMappings,
        FieldMappingsTypedDict,
        PostV1ContactSyncSupabaseRequest,
        PostV1ContactSyncSupabaseRequestTypedDict,
        PostV1ContactSyncSupabaseResponse,
        PostV1ContactSyncSupabaseResponseTypedDict,
        PostV1ContactSyncSupabaseSourceType,
    )
    from .post_v1_contact_sync_webhook_syncid_op import (
        PostV1ContactSyncWebhookSyncIDRequest,
        PostV1ContactSyncWebhookSyncIDRequestTypedDict,
        PostV1ContactSyncWebhookSyncIDResponse,
        PostV1ContactSyncWebhookSyncIDResponseTypedDict,
    )
    from .post_v1_topicsop import (
        PostV1TopicsRequest,
        PostV1TopicsRequestTypedDict,
        PostV1TopicsResponse,
        PostV1TopicsResponseTypedDict,
    )
    from .post_v1_unsubscribeop import (
        PostV1UnsubscribeRequest,
        PostV1UnsubscribeRequestTypedDict,
        PostV1UnsubscribeResponse,
        PostV1UnsubscribeResponseTypedDict,
    )
    from .put_v1_topics_id_op import (
        PutV1TopicsIDRequest,
        PutV1TopicsIDRequestBody,
        PutV1TopicsIDRequestBodyTypedDict,
        PutV1TopicsIDRequestTypedDict,
        PutV1TopicsIDResponse,
        PutV1TopicsIDResponseTypedDict,
    )
    from .replyto import ReplyTo, ReplyToTypedDict
    from .revokeapikeyop import RevokeAPIKeyRequest, RevokeAPIKeyRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .segment import Segment, SegmentTypedDict
    from .sendbroadcastop import SendBroadcastRequest, SendBroadcastRequestTypedDict
    from .sendbroadcastresponse import (
        SendBroadcastResponse,
        SendBroadcastResponseTypedDict,
    )
    from .sendemailrequest import (
        SendEmailRequest,
        SendEmailRequestTypedDict,
        To,
        ToTypedDict,
    )
    from .sendemailresponse import SendEmailResponse, SendEmailResponseTypedDict
    from .smtpcredentials import (
        Ports,
        PortsTypedDict,
        SMTPCredentials,
        SMTPCredentialsTypedDict,
    )
    from .success import Success, SuccessTypedDict
    from .teammember import Profiles, ProfilesTypedDict, TeamMember, TeamMemberTypedDict
    from .template import Template, TemplateTypedDict
    from .togglewebhookop import ToggleWebhookRequest, ToggleWebhookRequestTypedDict
    from .unsubscribesettings import UnsubscribeSettings, UnsubscribeSettingsTypedDict
    from .updatecontactop import (
        UpdateContactRequestRequest,
        UpdateContactRequestRequestTypedDict,
    )
    from .updatecontactrequest import (
        UpdateContactRequest,
        UpdateContactRequestTypedDict,
    )
    from .updatedomainop import (
        UpdateDomainRequestRequest,
        UpdateDomainRequestRequestTypedDict,
    )
    from .updatedomainrequest import UpdateDomainRequest, UpdateDomainRequestTypedDict
    from .updateorganizationrequest import (
        UpdateOrganizationRequest,
        UpdateOrganizationRequestTypedDict,
    )
    from .updatetemplateop import UpdateTemplateRequest, UpdateTemplateRequestTypedDict
    from .updateunsubscribesettingsrequest import (
        UpdateUnsubscribeSettingsRequest,
        UpdateUnsubscribeSettingsRequestTypedDict,
    )
    from .usagemetric import UsageMetric, UsageMetricTypedDict
    from .verifydomainop import VerifyDomainRequest, VerifyDomainRequestTypedDict
    from .webhook import Webhook, WebhookTypedDict
    from .webhookdelivery import WebhookDelivery, WebhookDeliveryTypedDict
    from .webhooktoggleresponse import (
        WebhookToggleResponse,
        WebhookToggleResponseTypedDict,
    )

__all__ = [
    "APIKey",
    "APIKeyListItem",
    "APIKeyListItemTypedDict",
    "APIKeyTypedDict",
    "AddContactToSegmentRequest",
    "AddContactToSegmentRequestTypedDict",
    "AddDomainRequest",
    "AddDomainRequestTypedDict",
    "Attachment",
    "AttachmentTypedDict",
    "Broadcast",
    "BroadcastTypedDict",
    "BulkCreateContactsRequest",
    "BulkCreateContactsRequestTypedDict",
    "BulkCreateContactsResponse",
    "BulkCreateContactsResponseTypedDict",
    "Connection",
    "ConnectionTypedDict",
    "Contact",
    "ContactListResponse",
    "ContactListResponseTypedDict",
    "ContactTypedDict",
    "CreateAPIKeyRequest",
    "CreateAPIKeyRequestTypedDict",
    "CreateBroadcastRequest",
    "CreateBroadcastRequestTypedDict",
    "CreateContactRequest",
    "CreateContactRequestTypedDict",
    "CreateSegmentRequest",
    "CreateSegmentRequestTypedDict",
    "CreateTemplateRequest",
    "CreateTemplateRequestTypedDict",
    "CreateWebhookRequest",
    "CreateWebhookRequestTypedDict",
    "DNSRecord",
    "DNSRecordTypedDict",
    "DNSVerificationStatus",
    "DNSVerificationStatusTypedDict",
    "DeleteContactRequest",
    "DeleteContactRequestTypedDict",
    "DeleteDomainRequest",
    "DeleteDomainRequestTypedDict",
    "DeleteTemplateRequest",
    "DeleteTemplateRequestTypedDict",
    "DeleteV1ContactSyncIDRequest",
    "DeleteV1ContactSyncIDRequestTypedDict",
    "DeleteV1ContactSyncIDResponse",
    "DeleteV1ContactSyncIDResponseTypedDict",
    "DeleteV1IntegrationsIDRequest",
    "DeleteV1IntegrationsIDRequestTypedDict",
    "DeleteV1IntegrationsIDResponse",
    "DeleteV1IntegrationsIDResponseTypedDict",
    "DeleteV1TopicsIDRequest",
    "DeleteV1TopicsIDRequestTypedDict",
    "DeleteV1TopicsIDResponse",
    "DeleteV1TopicsIDResponseTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "Domain",
    "DomainDNSRecords",
    "DomainDNSRecordsTypedDict",
    "DomainTypedDict",
    "DomainVerificationStatus",
    "DomainVerificationStatusTypedDict",
    "Email",
    "EmailEvent",
    "EmailEventTypedDict",
    "EmailMetrics",
    "EmailMetricsTypedDict",
    "EmailTypedDict",
    "FieldMappings",
    "FieldMappingsTypedDict",
    "GetBroadcastRequest",
    "GetBroadcastRequestTypedDict",
    "GetContactRequest",
    "GetContactRequestTypedDict",
    "GetDomainDNSStatusRequest",
    "GetDomainDNSStatusRequestTypedDict",
    "GetEmailRequest",
    "GetEmailRequestTypedDict",
    "GetTemplateRequest",
    "GetTemplateRequestTypedDict",
    "GetUsageRequest",
    "GetUsageRequestTypedDict",
    "GetV1BillingUsageResponse",
    "GetV1BillingUsageResponseTypedDict",
    "GetV1ContactSyncResponse",
    "GetV1ContactSyncResponseTypedDict",
    "GetV1ContactSyncSourceType",
    "GetV1IntegrationsConnectionsResponse",
    "GetV1IntegrationsConnectionsResponseTypedDict",
    "GetV1IntegrationsSupabaseCallbackRequest",
    "GetV1IntegrationsSupabaseCallbackRequestTypedDict",
    "GetV1IntegrationsVercelCallbackRequest",
    "GetV1IntegrationsVercelCallbackRequestTypedDict",
    "GetV1TopicsResponse",
    "GetV1TopicsResponseTypedDict",
    "GetV1TopicsTopic",
    "GetV1TopicsTopicTypedDict",
    "GetV1UnsubscribeOrganizationIDRequest",
    "GetV1UnsubscribeOrganizationIDRequestTypedDict",
    "GetV1UnsubscribeOrganizationIDResponse",
    "GetV1UnsubscribeOrganizationIDResponseTypedDict",
    "GetV1UnsubscribeOrganizationIDTopic",
    "GetV1UnsubscribeOrganizationIDTopicTypedDict",
    "GetWebhookDeliveriesRequest",
    "GetWebhookDeliveriesRequestTypedDict",
    "ListContactsRequest",
    "ListContactsRequestTypedDict",
    "ListEmailsRequest",
    "ListEmailsRequestTypedDict",
    "ListEmailsResponse",
    "ListEmailsResponseTypedDict",
    "ListLogsRequest",
    "ListLogsRequestTypedDict",
    "Organization",
    "OrganizationTypedDict",
    "Pagination",
    "PaginationTypedDict",
    "PlanType",
    "Ports",
    "PortsTypedDict",
    "PostV1BillingCheckoutRequest",
    "PostV1BillingCheckoutRequestTypedDict",
    "PostV1BillingCheckoutResponse",
    "PostV1BillingCheckoutResponseTypedDict",
    "PostV1BillingPortalResponse",
    "PostV1BillingPortalResponseTypedDict",
    "PostV1BillingWebhooksResponse",
    "PostV1BillingWebhooksResponseTypedDict",
    "PostV1ContactSyncSupabaseRequest",
    "PostV1ContactSyncSupabaseRequestTypedDict",
    "PostV1ContactSyncSupabaseResponse",
    "PostV1ContactSyncSupabaseResponseTypedDict",
    "PostV1ContactSyncSupabaseSourceType",
    "PostV1ContactSyncWebhookSyncIDRequest",
    "PostV1ContactSyncWebhookSyncIDRequestTypedDict",
    "PostV1ContactSyncWebhookSyncIDResponse",
    "PostV1ContactSyncWebhookSyncIDResponseTypedDict",
    "PostV1TopicsRequest",
    "PostV1TopicsRequestTypedDict",
    "PostV1TopicsResponse",
    "PostV1TopicsResponseTypedDict",
    "PostV1UnsubscribeRequest",
    "PostV1UnsubscribeRequestTypedDict",
    "PostV1UnsubscribeResponse",
    "PostV1UnsubscribeResponseTypedDict",
    "Profiles",
    "ProfilesTypedDict",
    "Provider",
    "PutV1TopicsIDRequest",
    "PutV1TopicsIDRequestBody",
    "PutV1TopicsIDRequestBodyTypedDict",
    "PutV1TopicsIDRequestTypedDict",
    "PutV1TopicsIDResponse",
    "PutV1TopicsIDResponseTypedDict",
    "ReplyTo",
    "ReplyToTypedDict",
    "RevokeAPIKeyRequest",
    "RevokeAPIKeyRequestTypedDict",
    "SMTPCredentials",
    "SMTPCredentialsTypedDict",
    "Security",
    "SecurityTypedDict",
    "Segment",
    "SegmentTypedDict",
    "SendBroadcastRequest",
    "SendBroadcastRequestTypedDict",
    "SendBroadcastResponse",
    "SendBroadcastResponseTypedDict",
    "SendEmailRequest",
    "SendEmailRequestTypedDict",
    "SendEmailResponse",
    "SendEmailResponseTypedDict",
    "Success",
    "SuccessTypedDict",
    "Sync",
    "SyncTypedDict",
    "TeamMember",
    "TeamMemberTypedDict",
    "Template",
    "TemplateTypedDict",
    "To",
    "ToTypedDict",
    "ToggleWebhookRequest",
    "ToggleWebhookRequestTypedDict",
    "Type",
    "UnsubscribeSettings",
    "UnsubscribeSettingsTypedDict",
    "UpdateContactRequest",
    "UpdateContactRequestRequest",
    "UpdateContactRequestRequestTypedDict",
    "UpdateContactRequestTypedDict",
    "UpdateDomainRequest",
    "UpdateDomainRequestRequest",
    "UpdateDomainRequestRequestTypedDict",
    "UpdateDomainRequestTypedDict",
    "UpdateOrganizationRequest",
    "UpdateOrganizationRequestTypedDict",
    "UpdateTemplateRequest",
    "UpdateTemplateRequestTypedDict",
    "UpdateUnsubscribeSettingsRequest",
    "UpdateUnsubscribeSettingsRequestTypedDict",
    "UsageMetric",
    "UsageMetricTypedDict",
    "VerifyDomainRequest",
    "VerifyDomainRequestTypedDict",
    "Webhook",
    "WebhookDelivery",
    "WebhookDeliveryTypedDict",
    "WebhookToggleResponse",
    "WebhookToggleResponseTypedDict",
    "WebhookTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AddContactToSegmentRequest": ".addcontacttosegmentop",
    "AddContactToSegmentRequestTypedDict": ".addcontacttosegmentop",
    "AddDomainRequest": ".adddomainrequest",
    "AddDomainRequestTypedDict": ".adddomainrequest",
    "APIKey": ".apikey",
    "APIKeyTypedDict": ".apikey",
    "APIKeyListItem": ".apikeylistitem",
    "APIKeyListItemTypedDict": ".apikeylistitem",
    "Attachment": ".attachment",
    "AttachmentTypedDict": ".attachment",
    "Broadcast": ".broadcast",
    "BroadcastTypedDict": ".broadcast",
    "BulkCreateContactsRequest": ".bulkcreatecontactsrequest",
    "BulkCreateContactsRequestTypedDict": ".bulkcreatecontactsrequest",
    "BulkCreateContactsResponse": ".bulkcreatecontactsresponse",
    "BulkCreateContactsResponseTypedDict": ".bulkcreatecontactsresponse",
    "Contact": ".contact",
    "ContactTypedDict": ".contact",
    "ContactListResponse": ".contactlistresponse",
    "ContactListResponseTypedDict": ".contactlistresponse",
    "CreateAPIKeyRequest": ".createapikeyrequest",
    "CreateAPIKeyRequestTypedDict": ".createapikeyrequest",
    "CreateBroadcastRequest": ".createbroadcastrequest",
    "CreateBroadcastRequestTypedDict": ".createbroadcastrequest",
    "CreateContactRequest": ".createcontactrequest",
    "CreateContactRequestTypedDict": ".createcontactrequest",
    "CreateSegmentRequest": ".createsegmentrequest",
    "CreateSegmentRequestTypedDict": ".createsegmentrequest",
    "CreateTemplateRequest": ".createtemplaterequest",
    "CreateTemplateRequestTypedDict": ".createtemplaterequest",
    "CreateWebhookRequest": ".createwebhookrequest",
    "CreateWebhookRequestTypedDict": ".createwebhookrequest",
    "DeleteV1ContactSyncIDRequest": ".delete_v1_contact_sync_id_op",
    "DeleteV1ContactSyncIDRequestTypedDict": ".delete_v1_contact_sync_id_op",
    "DeleteV1ContactSyncIDResponse": ".delete_v1_contact_sync_id_op",
    "DeleteV1ContactSyncIDResponseTypedDict": ".delete_v1_contact_sync_id_op",
    "DeleteV1IntegrationsIDRequest": ".delete_v1_integrations_id_op",
    "DeleteV1IntegrationsIDRequestTypedDict": ".delete_v1_integrations_id_op",
    "DeleteV1IntegrationsIDResponse": ".delete_v1_integrations_id_op",
    "DeleteV1IntegrationsIDResponseTypedDict": ".delete_v1_integrations_id_op",
    "DeleteV1TopicsIDRequest": ".delete_v1_topics_id_op",
    "DeleteV1TopicsIDRequestTypedDict": ".delete_v1_topics_id_op",
    "DeleteV1TopicsIDResponse": ".delete_v1_topics_id_op",
    "DeleteV1TopicsIDResponseTypedDict": ".delete_v1_topics_id_op",
    "DeleteContactRequest": ".deletecontactop",
    "DeleteContactRequestTypedDict": ".deletecontactop",
    "DeleteDomainRequest": ".deletedomainop",
    "DeleteDomainRequestTypedDict": ".deletedomainop",
    "DeleteTemplateRequest": ".deletetemplateop",
    "DeleteTemplateRequestTypedDict": ".deletetemplateop",
    "DeleteWebhookRequest": ".deletewebhookop",
    "DeleteWebhookRequestTypedDict": ".deletewebhookop",
    "DNSRecord": ".dnsrecord",
    "DNSRecordTypedDict": ".dnsrecord",
    "Type": ".dnsrecord",
    "DNSVerificationStatus": ".dnsverificationstatus",
    "DNSVerificationStatusTypedDict": ".dnsverificationstatus",
    "Domain": ".domain",
    "DomainTypedDict": ".domain",
    "DomainDNSRecords": ".domaindnsrecords",
    "DomainDNSRecordsTypedDict": ".domaindnsrecords",
    "DomainVerificationStatus": ".domainverificationstatus",
    "DomainVerificationStatusTypedDict": ".domainverificationstatus",
    "Email": ".email",
    "EmailTypedDict": ".email",
    "EmailEvent": ".emailevent",
    "EmailEventTypedDict": ".emailevent",
    "EmailMetrics": ".emailmetrics",
    "EmailMetricsTypedDict": ".emailmetrics",
    "GetV1BillingUsageResponse": ".get_v1_billing_usageop",
    "GetV1BillingUsageResponseTypedDict": ".get_v1_billing_usageop",
    "GetV1ContactSyncResponse": ".get_v1_contact_syncop",
    "GetV1ContactSyncResponseTypedDict": ".get_v1_contact_syncop",
    "GetV1ContactSyncSourceType": ".get_v1_contact_syncop",
    "Sync": ".get_v1_contact_syncop",
    "SyncTypedDict": ".get_v1_contact_syncop",
    "Connection": ".get_v1_integrations_connectionsop",
    "ConnectionTypedDict": ".get_v1_integrations_connectionsop",
    "GetV1IntegrationsConnectionsResponse": ".get_v1_integrations_connectionsop",
    "GetV1IntegrationsConnectionsResponseTypedDict": ".get_v1_integrations_connectionsop",
    "Provider": ".get_v1_integrations_connectionsop",
    "GetV1IntegrationsSupabaseCallbackRequest": ".get_v1_integrations_supabase_callbackop",
    "GetV1IntegrationsSupabaseCallbackRequestTypedDict": ".get_v1_integrations_supabase_callbackop",
    "GetV1IntegrationsVercelCallbackRequest": ".get_v1_integrations_vercel_callbackop",
    "GetV1IntegrationsVercelCallbackRequestTypedDict": ".get_v1_integrations_vercel_callbackop",
    "GetV1TopicsResponse": ".get_v1_topicsop",
    "GetV1TopicsResponseTypedDict": ".get_v1_topicsop",
    "GetV1TopicsTopic": ".get_v1_topicsop",
    "GetV1TopicsTopicTypedDict": ".get_v1_topicsop",
    "GetV1UnsubscribeOrganizationIDRequest": ".get_v1_unsubscribe_organizationid_op",
    "GetV1UnsubscribeOrganizationIDRequestTypedDict": ".get_v1_unsubscribe_organizationid_op",
    "GetV1UnsubscribeOrganizationIDResponse": ".get_v1_unsubscribe_organizationid_op",
    "GetV1UnsubscribeOrganizationIDResponseTypedDict": ".get_v1_unsubscribe_organizationid_op",
    "GetV1UnsubscribeOrganizationIDTopic": ".get_v1_unsubscribe_organizationid_op",
    "GetV1UnsubscribeOrganizationIDTopicTypedDict": ".get_v1_unsubscribe_organizationid_op",
    "GetBroadcastRequest": ".getbroadcastop",
    "GetBroadcastRequestTypedDict": ".getbroadcastop",
    "GetContactRequest": ".getcontactop",
    "GetContactRequestTypedDict": ".getcontactop",
    "GetDomainDNSStatusRequest": ".getdomaindnsstatusop",
    "GetDomainDNSStatusRequestTypedDict": ".getdomaindnsstatusop",
    "GetEmailRequest": ".getemailop",
    "GetEmailRequestTypedDict": ".getemailop",
    "GetTemplateRequest": ".gettemplateop",
    "GetTemplateRequestTypedDict": ".gettemplateop",
    "GetUsageRequest": ".getusageop",
    "GetUsageRequestTypedDict": ".getusageop",
    "GetWebhookDeliveriesRequest": ".getwebhookdeliveriesop",
    "GetWebhookDeliveriesRequestTypedDict": ".getwebhookdeliveriesop",
    "ListContactsRequest": ".listcontactsop",
    "ListContactsRequestTypedDict": ".listcontactsop",
    "ListEmailsRequest": ".listemailsop",
    "ListEmailsRequestTypedDict": ".listemailsop",
    "ListEmailsResponse": ".listemailsop",
    "ListEmailsResponseTypedDict": ".listemailsop",
    "Pagination": ".listemailsop",
    "PaginationTypedDict": ".listemailsop",
    "ListLogsRequest": ".listlogsop",
    "ListLogsRequestTypedDict": ".listlogsop",
    "Organization": ".organization",
    "OrganizationTypedDict": ".organization",
    "PlanType": ".post_v1_billing_checkoutop",
    "PostV1BillingCheckoutRequest": ".post_v1_billing_checkoutop",
    "PostV1BillingCheckoutRequestTypedDict": ".post_v1_billing_checkoutop",
    "PostV1BillingCheckoutResponse": ".post_v1_billing_checkoutop",
    "PostV1BillingCheckoutResponseTypedDict": ".post_v1_billing_checkoutop",
    "PostV1BillingPortalResponse": ".post_v1_billing_portalop",
    "PostV1BillingPortalResponseTypedDict": ".post_v1_billing_portalop",
    "PostV1BillingWebhooksResponse": ".post_v1_billing_webhooksop",
    "PostV1BillingWebhooksResponseTypedDict": ".post_v1_billing_webhooksop",
    "FieldMappings": ".post_v1_contact_sync_supabaseop",
    "FieldMappingsTypedDict": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncSupabaseRequest": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncSupabaseRequestTypedDict": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncSupabaseResponse": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncSupabaseResponseTypedDict": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncSupabaseSourceType": ".post_v1_contact_sync_supabaseop",
    "PostV1ContactSyncWebhookSyncIDRequest": ".post_v1_contact_sync_webhook_syncid_op",
    "PostV1ContactSyncWebhookSyncIDRequestTypedDict": ".post_v1_contact_sync_webhook_syncid_op",
    "PostV1ContactSyncWebhookSyncIDResponse": ".post_v1_contact_sync_webhook_syncid_op",
    "PostV1ContactSyncWebhookSyncIDResponseTypedDict": ".post_v1_contact_sync_webhook_syncid_op",
    "PostV1TopicsRequest": ".post_v1_topicsop",
    "PostV1TopicsRequestTypedDict": ".post_v1_topicsop",
    "PostV1TopicsResponse": ".post_v1_topicsop",
    "PostV1TopicsResponseTypedDict": ".post_v1_topicsop",
    "PostV1UnsubscribeRequest": ".post_v1_unsubscribeop",
    "PostV1UnsubscribeRequestTypedDict": ".post_v1_unsubscribeop",
    "PostV1UnsubscribeResponse": ".post_v1_unsubscribeop",
    "PostV1UnsubscribeResponseTypedDict": ".post_v1_unsubscribeop",
    "PutV1TopicsIDRequest": ".put_v1_topics_id_op",
    "PutV1TopicsIDRequestBody": ".put_v1_topics_id_op",
    "PutV1TopicsIDRequestBodyTypedDict": ".put_v1_topics_id_op",
    "PutV1TopicsIDRequestTypedDict": ".put_v1_topics_id_op",
    "PutV1TopicsIDResponse": ".put_v1_topics_id_op",
    "PutV1TopicsIDResponseTypedDict": ".put_v1_topics_id_op",
    "ReplyTo": ".replyto",
    "ReplyToTypedDict": ".replyto",
    "RevokeAPIKeyRequest": ".revokeapikeyop",
    "RevokeAPIKeyRequestTypedDict": ".revokeapikeyop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Segment": ".segment",
    "SegmentTypedDict": ".segment",
    "SendBroadcastRequest": ".sendbroadcastop",
    "SendBroadcastRequestTypedDict": ".sendbroadcastop",
    "SendBroadcastResponse": ".sendbroadcastresponse",
    "SendBroadcastResponseTypedDict": ".sendbroadcastresponse",
    "SendEmailRequest": ".sendemailrequest",
    "SendEmailRequestTypedDict": ".sendemailrequest",
    "To": ".sendemailrequest",
    "ToTypedDict": ".sendemailrequest",
    "SendEmailResponse": ".sendemailresponse",
    "SendEmailResponseTypedDict": ".sendemailresponse",
    "Ports": ".smtpcredentials",
    "PortsTypedDict": ".smtpcredentials",
    "SMTPCredentials": ".smtpcredentials",
    "SMTPCredentialsTypedDict": ".smtpcredentials",
    "Success": ".success",
    "SuccessTypedDict": ".success",
    "Profiles": ".teammember",
    "ProfilesTypedDict": ".teammember",
    "TeamMember": ".teammember",
    "TeamMemberTypedDict": ".teammember",
    "Template": ".template",
    "TemplateTypedDict": ".template",
    "ToggleWebhookRequest": ".togglewebhookop",
    "ToggleWebhookRequestTypedDict": ".togglewebhookop",
    "UnsubscribeSettings": ".unsubscribesettings",
    "UnsubscribeSettingsTypedDict": ".unsubscribesettings",
    "UpdateContactRequestRequest": ".updatecontactop",
    "UpdateContactRequestRequestTypedDict": ".updatecontactop",
    "UpdateContactRequest": ".updatecontactrequest",
    "UpdateContactRequestTypedDict": ".updatecontactrequest",
    "UpdateDomainRequestRequest": ".updatedomainop",
    "UpdateDomainRequestRequestTypedDict": ".updatedomainop",
    "UpdateDomainRequest": ".updatedomainrequest",
    "UpdateDomainRequestTypedDict": ".updatedomainrequest",
    "UpdateOrganizationRequest": ".updateorganizationrequest",
    "UpdateOrganizationRequestTypedDict": ".updateorganizationrequest",
    "UpdateTemplateRequest": ".updatetemplateop",
    "UpdateTemplateRequestTypedDict": ".updatetemplateop",
    "UpdateUnsubscribeSettingsRequest": ".updateunsubscribesettingsrequest",
    "UpdateUnsubscribeSettingsRequestTypedDict": ".updateunsubscribesettingsrequest",
    "UsageMetric": ".usagemetric",
    "UsageMetricTypedDict": ".usagemetric",
    "VerifyDomainRequest": ".verifydomainop",
    "VerifyDomainRequestTypedDict": ".verifydomainop",
    "Webhook": ".webhook",
    "WebhookTypedDict": ".webhook",
    "WebhookDelivery": ".webhookdelivery",
    "WebhookDeliveryTypedDict": ".webhookdelivery",
    "WebhookToggleResponse": ".webhooktoggleresponse",
    "WebhookToggleResponseTypedDict": ".webhooktoggleresponse",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
