"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from emailr.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .acceptinvitationop import (
        AcceptInvitationRequest,
        AcceptInvitationRequestTypedDict,
        AcceptInvitationResponse,
        AcceptInvitationResponseTypedDict,
    )
    from .addcontacttosegmentop import (
        AddContactToSegmentRequest,
        AddContactToSegmentRequestTypedDict,
    )
    from .adddomainrequest import AddDomainRequest, AddDomainRequestTypedDict
    from .attachment import Attachment, AttachmentTypedDict
    from .broadcast import Broadcast, BroadcastTypedDict
    from .bulkaddcontactstosegmentop import (
        BulkAddContactsToSegmentRequestRequest,
        BulkAddContactsToSegmentRequestRequestTypedDict,
    )
    from .bulkaddcontactstosegmentrequest import (
        BulkAddContactsToSegmentRequest,
        BulkAddContactsToSegmentRequestTypedDict,
    )
    from .bulkaddcontactstosegmentresponse import (
        BulkAddContactsToSegmentResponse,
        BulkAddContactsToSegmentResponseTypedDict,
    )
    from .bulkcreatecontactsrequest import (
        BulkCreateContactsRequest,
        BulkCreateContactsRequestTypedDict,
    )
    from .bulkcreatecontactsresponse import (
        BulkCreateContactsResponse,
        BulkCreateContactsResponseTypedDict,
    )
    from .cancelinvitationop import (
        CancelInvitationRequest,
        CancelInvitationRequestTypedDict,
    )
    from .columnmapping import ColumnMapping, ColumnMappingTypedDict
    from .contact import (
        Contact,
        ContactMetadata,
        ContactMetadataTypedDict,
        ContactTypedDict,
    )
    from .contactlistresponse import ContactListResponse, ContactListResponseTypedDict
    from .createbroadcastrequest import (
        CreateBroadcastRequest,
        CreateBroadcastRequestTypedDict,
    )
    from .createcontactrequest import (
        CreateContactRequest,
        CreateContactRequestMetadata,
        CreateContactRequestMetadataTypedDict,
        CreateContactRequestTypedDict,
    )
    from .createforwardingruleop import (
        CreateForwardingRuleRequest,
        CreateForwardingRuleRequestTypedDict,
        CreateForwardingRuleResponse,
        CreateForwardingRuleResponseTypedDict,
    )
    from .createinvitationrequest import (
        CreateInvitationRequest,
        CreateInvitationRequestRole,
        CreateInvitationRequestTypedDict,
    )
    from .createpropertydefinitionrequest import (
        CreatePropertyDefinitionRequest,
        CreatePropertyDefinitionRequestType,
        CreatePropertyDefinitionRequestTypedDict,
    )
    from .createsegmentrequest import (
        CreateSegmentRequest,
        CreateSegmentRequestType,
        CreateSegmentRequestTypedDict,
    )
    from .createtemplaterequest import (
        CreateTemplateRequest,
        CreateTemplateRequestTypedDict,
    )
    from .createwebhookrequest import (
        CreateWebhookRequest,
        CreateWebhookRequestTypedDict,
    )
    from .csvimportpreviewrequest import (
        CSVImportPreviewRequest,
        CSVImportPreviewRequestTypedDict,
    )
    from .csvimportpreviewresponse import (
        CSVImportPreviewResponse,
        CSVImportPreviewResponseTypedDict,
    )
    from .csvimportrequest import (
        CSVImportRequest,
        CSVImportRequestTypedDict,
        HandleMissing,
    )
    from .csvimportresponse import CSVImportResponse, CSVImportResponseTypedDict
    from .deletecontactop import DeleteContactRequest, DeleteContactRequestTypedDict
    from .deletedomainop import DeleteDomainRequest, DeleteDomainRequestTypedDict
    from .deleteforwardingruleop import (
        DeleteForwardingRuleRequest,
        DeleteForwardingRuleRequestTypedDict,
        DeleteForwardingRuleResponse,
        DeleteForwardingRuleResponseTypedDict,
    )
    from .deletepropertydefinitionop import (
        DeletePropertyDefinitionRequest,
        DeletePropertyDefinitionRequestTypedDict,
    )
    from .deletesegmentop import DeleteSegmentRequest, DeleteSegmentRequestTypedDict
    from .deletetemplateop import DeleteTemplateRequest, DeleteTemplateRequestTypedDict
    from .deletewebhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .dnsrecord import DNSRecord, DNSRecordType, DNSRecordTypedDict
    from .dnsverificationstatus import (
        DNSVerificationStatus,
        DNSVerificationStatusTypedDict,
    )
    from .domain import Domain, DomainTypedDict
    from .domaindnsrecords import DomainDNSRecords, DomainDNSRecordsTypedDict
    from .domainverificationstatus import (
        DomainVerificationStatus,
        DomainVerificationStatusTypedDict,
    )
    from .email import Email, EmailTypedDict
    from .filterconditions import FilterConditions, FilterConditionsTypedDict, Logic
    from .filterrule import FilterRule, FilterRuleTypedDict, Operator
    from .forwardemailop import (
        ForwardEmailRequest,
        ForwardEmailRequestTypedDict,
        ForwardEmailTo,
        ForwardEmailToTypedDict,
    )
    from .getbroadcastop import GetBroadcastRequest, GetBroadcastRequestTypedDict
    from .getcontactlimitop import (
        GetContactLimitResponse,
        GetContactLimitResponseTypedDict,
    )
    from .getcontactop import GetContactRequest, GetContactRequestTypedDict
    from .getdomaindnsstatusop import (
        GetDomainDNSStatusRequest,
        GetDomainDNSStatusRequestTypedDict,
    )
    from .getdomainop import GetDomainRequest, GetDomainRequestTypedDict
    from .getemailop import GetEmailRequest, GetEmailRequestTypedDict
    from .getinvitationdetailsop import (
        GetInvitationDetailsRequest,
        GetInvitationDetailsRequestTypedDict,
    )
    from .getsegmentcontactsop import (
        GetSegmentContactsRequest,
        GetSegmentContactsRequestTypedDict,
    )
    from .gettemplateop import GetTemplateRequest, GetTemplateRequestTypedDict
    from .gettemplatepreviewop import (
        GetTemplatePreviewRequest,
        GetTemplatePreviewRequestTypedDict,
    )
    from .getwebhookdeliveriesop import (
        GetWebhookDeliveriesRequest,
        GetWebhookDeliveriesRequestTypedDict,
    )
    from .importerror import ImportErrorT, ImportErrorTTypedDict
    from .invitation import Invitation, InvitationTypedDict
    from .invitationdetails import (
        InvitationDetails,
        InvitationDetailsRole,
        InvitationDetailsTypedDict,
    )
    from .invitationlistresponse import (
        InvitationListResponse,
        InvitationListResponseTypedDict,
    )
    from .invitationrole import InvitationRole
    from .invitationstatus import InvitationStatus
    from .listcontactsop import ListContactsRequest, ListContactsRequestTypedDict
    from .listemailsop import (
        ListEmailsRequest,
        ListEmailsRequestTypedDict,
        ListEmailsResponse,
        ListEmailsResponseTypedDict,
        Pagination,
        PaginationTypedDict,
    )
    from .listforwardingrulesop import (
        Data,
        DataTypedDict,
        ListForwardingRulesResponse,
        ListForwardingRulesResponseTypedDict,
    )
    from .propertydefinition import PropertyDefinition, PropertyDefinitionTypedDict
    from .propertytype import PropertyType
    from .publishtemplateop import (
        PublishTemplateRequest,
        PublishTemplateRequestTypedDict,
    )
    from .replyto import ReplyTo, ReplyToTypedDict
    from .security import Security, SecurityTypedDict
    from .segment import Segment, SegmentTypedDict
    from .segmentcontactsresponse import (
        SegmentContactsResponse,
        SegmentContactsResponseTypedDict,
    )
    from .segmenttype import SegmentType
    from .sendbroadcastop import SendBroadcastRequest, SendBroadcastRequestTypedDict
    from .sendbroadcastresponse import (
        SendBroadcastResponse,
        SendBroadcastResponseTypedDict,
    )
    from .sendemailrequest import (
        Bcc,
        BccTypedDict,
        Cc,
        CcTypedDict,
        SendEmailRequest,
        SendEmailRequestTypedDict,
        To,
        ToTypedDict,
    )
    from .sendemailresponse import SendEmailResponse, SendEmailResponseTypedDict
    from .success import Success, SuccessTypedDict
    from .template import Template, TemplateTypedDict
    from .togglewebhookop import ToggleWebhookRequest, ToggleWebhookRequestTypedDict
    from .updatecontactop import (
        UpdateContactRequestRequest,
        UpdateContactRequestRequestTypedDict,
    )
    from .updatecontactrequest import (
        UpdateContactRequest,
        UpdateContactRequestMetadata,
        UpdateContactRequestMetadataTypedDict,
        UpdateContactRequestTypedDict,
    )
    from .updatedomainop import (
        UpdateDomainRequestRequest,
        UpdateDomainRequestRequestTypedDict,
    )
    from .updatedomainrequest import UpdateDomainRequest, UpdateDomainRequestTypedDict
    from .updatepreviewrequest import (
        UpdatePreviewRequest,
        UpdatePreviewRequestTypedDict,
    )
    from .updatepreviewresponse import (
        UpdatePreviewResponse,
        UpdatePreviewResponseTypedDict,
    )
    from .updatesegmentop import (
        UpdateSegmentRequestRequest,
        UpdateSegmentRequestRequestTypedDict,
    )
    from .updatesegmentrequest import (
        UpdateSegmentRequest,
        UpdateSegmentRequestTypedDict,
    )
    from .updatetemplateop import (
        UpdateTemplateRequestRequest,
        UpdateTemplateRequestRequestTypedDict,
    )
    from .updatetemplatepreviewop import (
        UpdateTemplatePreviewRequest,
        UpdateTemplatePreviewRequestTypedDict,
    )
    from .updatetemplaterequest import (
        UpdateTemplateRequest,
        UpdateTemplateRequestTypedDict,
    )
    from .verifydomainop import VerifyDomainRequest, VerifyDomainRequestTypedDict
    from .webhook import Webhook, WebhookTypedDict
    from .webhookdelivery import WebhookDelivery, WebhookDeliveryTypedDict
    from .webhooktoggleresponse import (
        WebhookToggleResponse,
        WebhookToggleResponseTypedDict,
    )

__all__ = [
    "AcceptInvitationRequest",
    "AcceptInvitationRequestTypedDict",
    "AcceptInvitationResponse",
    "AcceptInvitationResponseTypedDict",
    "AddContactToSegmentRequest",
    "AddContactToSegmentRequestTypedDict",
    "AddDomainRequest",
    "AddDomainRequestTypedDict",
    "Attachment",
    "AttachmentTypedDict",
    "Bcc",
    "BccTypedDict",
    "Broadcast",
    "BroadcastTypedDict",
    "BulkAddContactsToSegmentRequest",
    "BulkAddContactsToSegmentRequestRequest",
    "BulkAddContactsToSegmentRequestRequestTypedDict",
    "BulkAddContactsToSegmentRequestTypedDict",
    "BulkAddContactsToSegmentResponse",
    "BulkAddContactsToSegmentResponseTypedDict",
    "BulkCreateContactsRequest",
    "BulkCreateContactsRequestTypedDict",
    "BulkCreateContactsResponse",
    "BulkCreateContactsResponseTypedDict",
    "CSVImportPreviewRequest",
    "CSVImportPreviewRequestTypedDict",
    "CSVImportPreviewResponse",
    "CSVImportPreviewResponseTypedDict",
    "CSVImportRequest",
    "CSVImportRequestTypedDict",
    "CSVImportResponse",
    "CSVImportResponseTypedDict",
    "CancelInvitationRequest",
    "CancelInvitationRequestTypedDict",
    "Cc",
    "CcTypedDict",
    "ColumnMapping",
    "ColumnMappingTypedDict",
    "Contact",
    "ContactListResponse",
    "ContactListResponseTypedDict",
    "ContactMetadata",
    "ContactMetadataTypedDict",
    "ContactTypedDict",
    "CreateBroadcastRequest",
    "CreateBroadcastRequestTypedDict",
    "CreateContactRequest",
    "CreateContactRequestMetadata",
    "CreateContactRequestMetadataTypedDict",
    "CreateContactRequestTypedDict",
    "CreateForwardingRuleRequest",
    "CreateForwardingRuleRequestTypedDict",
    "CreateForwardingRuleResponse",
    "CreateForwardingRuleResponseTypedDict",
    "CreateInvitationRequest",
    "CreateInvitationRequestRole",
    "CreateInvitationRequestTypedDict",
    "CreatePropertyDefinitionRequest",
    "CreatePropertyDefinitionRequestType",
    "CreatePropertyDefinitionRequestTypedDict",
    "CreateSegmentRequest",
    "CreateSegmentRequestType",
    "CreateSegmentRequestTypedDict",
    "CreateTemplateRequest",
    "CreateTemplateRequestTypedDict",
    "CreateWebhookRequest",
    "CreateWebhookRequestTypedDict",
    "DNSRecord",
    "DNSRecordType",
    "DNSRecordTypedDict",
    "DNSVerificationStatus",
    "DNSVerificationStatusTypedDict",
    "Data",
    "DataTypedDict",
    "DeleteContactRequest",
    "DeleteContactRequestTypedDict",
    "DeleteDomainRequest",
    "DeleteDomainRequestTypedDict",
    "DeleteForwardingRuleRequest",
    "DeleteForwardingRuleRequestTypedDict",
    "DeleteForwardingRuleResponse",
    "DeleteForwardingRuleResponseTypedDict",
    "DeletePropertyDefinitionRequest",
    "DeletePropertyDefinitionRequestTypedDict",
    "DeleteSegmentRequest",
    "DeleteSegmentRequestTypedDict",
    "DeleteTemplateRequest",
    "DeleteTemplateRequestTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "Domain",
    "DomainDNSRecords",
    "DomainDNSRecordsTypedDict",
    "DomainTypedDict",
    "DomainVerificationStatus",
    "DomainVerificationStatusTypedDict",
    "Email",
    "EmailTypedDict",
    "FilterConditions",
    "FilterConditionsTypedDict",
    "FilterRule",
    "FilterRuleTypedDict",
    "ForwardEmailRequest",
    "ForwardEmailRequestTypedDict",
    "ForwardEmailTo",
    "ForwardEmailToTypedDict",
    "GetBroadcastRequest",
    "GetBroadcastRequestTypedDict",
    "GetContactLimitResponse",
    "GetContactLimitResponseTypedDict",
    "GetContactRequest",
    "GetContactRequestTypedDict",
    "GetDomainDNSStatusRequest",
    "GetDomainDNSStatusRequestTypedDict",
    "GetDomainRequest",
    "GetDomainRequestTypedDict",
    "GetEmailRequest",
    "GetEmailRequestTypedDict",
    "GetInvitationDetailsRequest",
    "GetInvitationDetailsRequestTypedDict",
    "GetSegmentContactsRequest",
    "GetSegmentContactsRequestTypedDict",
    "GetTemplatePreviewRequest",
    "GetTemplatePreviewRequestTypedDict",
    "GetTemplateRequest",
    "GetTemplateRequestTypedDict",
    "GetWebhookDeliveriesRequest",
    "GetWebhookDeliveriesRequestTypedDict",
    "HandleMissing",
    "ImportErrorT",
    "ImportErrorTTypedDict",
    "Invitation",
    "InvitationDetails",
    "InvitationDetailsRole",
    "InvitationDetailsTypedDict",
    "InvitationListResponse",
    "InvitationListResponseTypedDict",
    "InvitationRole",
    "InvitationStatus",
    "InvitationTypedDict",
    "ListContactsRequest",
    "ListContactsRequestTypedDict",
    "ListEmailsRequest",
    "ListEmailsRequestTypedDict",
    "ListEmailsResponse",
    "ListEmailsResponseTypedDict",
    "ListForwardingRulesResponse",
    "ListForwardingRulesResponseTypedDict",
    "Logic",
    "Operator",
    "Pagination",
    "PaginationTypedDict",
    "PropertyDefinition",
    "PropertyDefinitionTypedDict",
    "PropertyType",
    "PublishTemplateRequest",
    "PublishTemplateRequestTypedDict",
    "ReplyTo",
    "ReplyToTypedDict",
    "Security",
    "SecurityTypedDict",
    "Segment",
    "SegmentContactsResponse",
    "SegmentContactsResponseTypedDict",
    "SegmentType",
    "SegmentTypedDict",
    "SendBroadcastRequest",
    "SendBroadcastRequestTypedDict",
    "SendBroadcastResponse",
    "SendBroadcastResponseTypedDict",
    "SendEmailRequest",
    "SendEmailRequestTypedDict",
    "SendEmailResponse",
    "SendEmailResponseTypedDict",
    "Success",
    "SuccessTypedDict",
    "Template",
    "TemplateTypedDict",
    "To",
    "ToTypedDict",
    "ToggleWebhookRequest",
    "ToggleWebhookRequestTypedDict",
    "UpdateContactRequest",
    "UpdateContactRequestMetadata",
    "UpdateContactRequestMetadataTypedDict",
    "UpdateContactRequestRequest",
    "UpdateContactRequestRequestTypedDict",
    "UpdateContactRequestTypedDict",
    "UpdateDomainRequest",
    "UpdateDomainRequestRequest",
    "UpdateDomainRequestRequestTypedDict",
    "UpdateDomainRequestTypedDict",
    "UpdatePreviewRequest",
    "UpdatePreviewRequestTypedDict",
    "UpdatePreviewResponse",
    "UpdatePreviewResponseTypedDict",
    "UpdateSegmentRequest",
    "UpdateSegmentRequestRequest",
    "UpdateSegmentRequestRequestTypedDict",
    "UpdateSegmentRequestTypedDict",
    "UpdateTemplatePreviewRequest",
    "UpdateTemplatePreviewRequestTypedDict",
    "UpdateTemplateRequest",
    "UpdateTemplateRequestRequest",
    "UpdateTemplateRequestRequestTypedDict",
    "UpdateTemplateRequestTypedDict",
    "VerifyDomainRequest",
    "VerifyDomainRequestTypedDict",
    "Webhook",
    "WebhookDelivery",
    "WebhookDeliveryTypedDict",
    "WebhookToggleResponse",
    "WebhookToggleResponseTypedDict",
    "WebhookTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AcceptInvitationRequest": ".acceptinvitationop",
    "AcceptInvitationRequestTypedDict": ".acceptinvitationop",
    "AcceptInvitationResponse": ".acceptinvitationop",
    "AcceptInvitationResponseTypedDict": ".acceptinvitationop",
    "AddContactToSegmentRequest": ".addcontacttosegmentop",
    "AddContactToSegmentRequestTypedDict": ".addcontacttosegmentop",
    "AddDomainRequest": ".adddomainrequest",
    "AddDomainRequestTypedDict": ".adddomainrequest",
    "Attachment": ".attachment",
    "AttachmentTypedDict": ".attachment",
    "Broadcast": ".broadcast",
    "BroadcastTypedDict": ".broadcast",
    "BulkAddContactsToSegmentRequestRequest": ".bulkaddcontactstosegmentop",
    "BulkAddContactsToSegmentRequestRequestTypedDict": ".bulkaddcontactstosegmentop",
    "BulkAddContactsToSegmentRequest": ".bulkaddcontactstosegmentrequest",
    "BulkAddContactsToSegmentRequestTypedDict": ".bulkaddcontactstosegmentrequest",
    "BulkAddContactsToSegmentResponse": ".bulkaddcontactstosegmentresponse",
    "BulkAddContactsToSegmentResponseTypedDict": ".bulkaddcontactstosegmentresponse",
    "BulkCreateContactsRequest": ".bulkcreatecontactsrequest",
    "BulkCreateContactsRequestTypedDict": ".bulkcreatecontactsrequest",
    "BulkCreateContactsResponse": ".bulkcreatecontactsresponse",
    "BulkCreateContactsResponseTypedDict": ".bulkcreatecontactsresponse",
    "CancelInvitationRequest": ".cancelinvitationop",
    "CancelInvitationRequestTypedDict": ".cancelinvitationop",
    "ColumnMapping": ".columnmapping",
    "ColumnMappingTypedDict": ".columnmapping",
    "Contact": ".contact",
    "ContactMetadata": ".contact",
    "ContactMetadataTypedDict": ".contact",
    "ContactTypedDict": ".contact",
    "ContactListResponse": ".contactlistresponse",
    "ContactListResponseTypedDict": ".contactlistresponse",
    "CreateBroadcastRequest": ".createbroadcastrequest",
    "CreateBroadcastRequestTypedDict": ".createbroadcastrequest",
    "CreateContactRequest": ".createcontactrequest",
    "CreateContactRequestMetadata": ".createcontactrequest",
    "CreateContactRequestMetadataTypedDict": ".createcontactrequest",
    "CreateContactRequestTypedDict": ".createcontactrequest",
    "CreateForwardingRuleRequest": ".createforwardingruleop",
    "CreateForwardingRuleRequestTypedDict": ".createforwardingruleop",
    "CreateForwardingRuleResponse": ".createforwardingruleop",
    "CreateForwardingRuleResponseTypedDict": ".createforwardingruleop",
    "CreateInvitationRequest": ".createinvitationrequest",
    "CreateInvitationRequestRole": ".createinvitationrequest",
    "CreateInvitationRequestTypedDict": ".createinvitationrequest",
    "CreatePropertyDefinitionRequest": ".createpropertydefinitionrequest",
    "CreatePropertyDefinitionRequestType": ".createpropertydefinitionrequest",
    "CreatePropertyDefinitionRequestTypedDict": ".createpropertydefinitionrequest",
    "CreateSegmentRequest": ".createsegmentrequest",
    "CreateSegmentRequestType": ".createsegmentrequest",
    "CreateSegmentRequestTypedDict": ".createsegmentrequest",
    "CreateTemplateRequest": ".createtemplaterequest",
    "CreateTemplateRequestTypedDict": ".createtemplaterequest",
    "CreateWebhookRequest": ".createwebhookrequest",
    "CreateWebhookRequestTypedDict": ".createwebhookrequest",
    "CSVImportPreviewRequest": ".csvimportpreviewrequest",
    "CSVImportPreviewRequestTypedDict": ".csvimportpreviewrequest",
    "CSVImportPreviewResponse": ".csvimportpreviewresponse",
    "CSVImportPreviewResponseTypedDict": ".csvimportpreviewresponse",
    "CSVImportRequest": ".csvimportrequest",
    "CSVImportRequestTypedDict": ".csvimportrequest",
    "HandleMissing": ".csvimportrequest",
    "CSVImportResponse": ".csvimportresponse",
    "CSVImportResponseTypedDict": ".csvimportresponse",
    "DeleteContactRequest": ".deletecontactop",
    "DeleteContactRequestTypedDict": ".deletecontactop",
    "DeleteDomainRequest": ".deletedomainop",
    "DeleteDomainRequestTypedDict": ".deletedomainop",
    "DeleteForwardingRuleRequest": ".deleteforwardingruleop",
    "DeleteForwardingRuleRequestTypedDict": ".deleteforwardingruleop",
    "DeleteForwardingRuleResponse": ".deleteforwardingruleop",
    "DeleteForwardingRuleResponseTypedDict": ".deleteforwardingruleop",
    "DeletePropertyDefinitionRequest": ".deletepropertydefinitionop",
    "DeletePropertyDefinitionRequestTypedDict": ".deletepropertydefinitionop",
    "DeleteSegmentRequest": ".deletesegmentop",
    "DeleteSegmentRequestTypedDict": ".deletesegmentop",
    "DeleteTemplateRequest": ".deletetemplateop",
    "DeleteTemplateRequestTypedDict": ".deletetemplateop",
    "DeleteWebhookRequest": ".deletewebhookop",
    "DeleteWebhookRequestTypedDict": ".deletewebhookop",
    "DNSRecord": ".dnsrecord",
    "DNSRecordType": ".dnsrecord",
    "DNSRecordTypedDict": ".dnsrecord",
    "DNSVerificationStatus": ".dnsverificationstatus",
    "DNSVerificationStatusTypedDict": ".dnsverificationstatus",
    "Domain": ".domain",
    "DomainTypedDict": ".domain",
    "DomainDNSRecords": ".domaindnsrecords",
    "DomainDNSRecordsTypedDict": ".domaindnsrecords",
    "DomainVerificationStatus": ".domainverificationstatus",
    "DomainVerificationStatusTypedDict": ".domainverificationstatus",
    "Email": ".email",
    "EmailTypedDict": ".email",
    "FilterConditions": ".filterconditions",
    "FilterConditionsTypedDict": ".filterconditions",
    "Logic": ".filterconditions",
    "FilterRule": ".filterrule",
    "FilterRuleTypedDict": ".filterrule",
    "Operator": ".filterrule",
    "ForwardEmailRequest": ".forwardemailop",
    "ForwardEmailRequestTypedDict": ".forwardemailop",
    "ForwardEmailTo": ".forwardemailop",
    "ForwardEmailToTypedDict": ".forwardemailop",
    "GetBroadcastRequest": ".getbroadcastop",
    "GetBroadcastRequestTypedDict": ".getbroadcastop",
    "GetContactLimitResponse": ".getcontactlimitop",
    "GetContactLimitResponseTypedDict": ".getcontactlimitop",
    "GetContactRequest": ".getcontactop",
    "GetContactRequestTypedDict": ".getcontactop",
    "GetDomainDNSStatusRequest": ".getdomaindnsstatusop",
    "GetDomainDNSStatusRequestTypedDict": ".getdomaindnsstatusop",
    "GetDomainRequest": ".getdomainop",
    "GetDomainRequestTypedDict": ".getdomainop",
    "GetEmailRequest": ".getemailop",
    "GetEmailRequestTypedDict": ".getemailop",
    "GetInvitationDetailsRequest": ".getinvitationdetailsop",
    "GetInvitationDetailsRequestTypedDict": ".getinvitationdetailsop",
    "GetSegmentContactsRequest": ".getsegmentcontactsop",
    "GetSegmentContactsRequestTypedDict": ".getsegmentcontactsop",
    "GetTemplateRequest": ".gettemplateop",
    "GetTemplateRequestTypedDict": ".gettemplateop",
    "GetTemplatePreviewRequest": ".gettemplatepreviewop",
    "GetTemplatePreviewRequestTypedDict": ".gettemplatepreviewop",
    "GetWebhookDeliveriesRequest": ".getwebhookdeliveriesop",
    "GetWebhookDeliveriesRequestTypedDict": ".getwebhookdeliveriesop",
    "ImportErrorT": ".importerror",
    "ImportErrorTTypedDict": ".importerror",
    "Invitation": ".invitation",
    "InvitationTypedDict": ".invitation",
    "InvitationDetails": ".invitationdetails",
    "InvitationDetailsRole": ".invitationdetails",
    "InvitationDetailsTypedDict": ".invitationdetails",
    "InvitationListResponse": ".invitationlistresponse",
    "InvitationListResponseTypedDict": ".invitationlistresponse",
    "InvitationRole": ".invitationrole",
    "InvitationStatus": ".invitationstatus",
    "ListContactsRequest": ".listcontactsop",
    "ListContactsRequestTypedDict": ".listcontactsop",
    "ListEmailsRequest": ".listemailsop",
    "ListEmailsRequestTypedDict": ".listemailsop",
    "ListEmailsResponse": ".listemailsop",
    "ListEmailsResponseTypedDict": ".listemailsop",
    "Pagination": ".listemailsop",
    "PaginationTypedDict": ".listemailsop",
    "Data": ".listforwardingrulesop",
    "DataTypedDict": ".listforwardingrulesop",
    "ListForwardingRulesResponse": ".listforwardingrulesop",
    "ListForwardingRulesResponseTypedDict": ".listforwardingrulesop",
    "PropertyDefinition": ".propertydefinition",
    "PropertyDefinitionTypedDict": ".propertydefinition",
    "PropertyType": ".propertytype",
    "PublishTemplateRequest": ".publishtemplateop",
    "PublishTemplateRequestTypedDict": ".publishtemplateop",
    "ReplyTo": ".replyto",
    "ReplyToTypedDict": ".replyto",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Segment": ".segment",
    "SegmentTypedDict": ".segment",
    "SegmentContactsResponse": ".segmentcontactsresponse",
    "SegmentContactsResponseTypedDict": ".segmentcontactsresponse",
    "SegmentType": ".segmenttype",
    "SendBroadcastRequest": ".sendbroadcastop",
    "SendBroadcastRequestTypedDict": ".sendbroadcastop",
    "SendBroadcastResponse": ".sendbroadcastresponse",
    "SendBroadcastResponseTypedDict": ".sendbroadcastresponse",
    "Bcc": ".sendemailrequest",
    "BccTypedDict": ".sendemailrequest",
    "Cc": ".sendemailrequest",
    "CcTypedDict": ".sendemailrequest",
    "SendEmailRequest": ".sendemailrequest",
    "SendEmailRequestTypedDict": ".sendemailrequest",
    "To": ".sendemailrequest",
    "ToTypedDict": ".sendemailrequest",
    "SendEmailResponse": ".sendemailresponse",
    "SendEmailResponseTypedDict": ".sendemailresponse",
    "Success": ".success",
    "SuccessTypedDict": ".success",
    "Template": ".template",
    "TemplateTypedDict": ".template",
    "ToggleWebhookRequest": ".togglewebhookop",
    "ToggleWebhookRequestTypedDict": ".togglewebhookop",
    "UpdateContactRequestRequest": ".updatecontactop",
    "UpdateContactRequestRequestTypedDict": ".updatecontactop",
    "UpdateContactRequest": ".updatecontactrequest",
    "UpdateContactRequestMetadata": ".updatecontactrequest",
    "UpdateContactRequestMetadataTypedDict": ".updatecontactrequest",
    "UpdateContactRequestTypedDict": ".updatecontactrequest",
    "UpdateDomainRequestRequest": ".updatedomainop",
    "UpdateDomainRequestRequestTypedDict": ".updatedomainop",
    "UpdateDomainRequest": ".updatedomainrequest",
    "UpdateDomainRequestTypedDict": ".updatedomainrequest",
    "UpdatePreviewRequest": ".updatepreviewrequest",
    "UpdatePreviewRequestTypedDict": ".updatepreviewrequest",
    "UpdatePreviewResponse": ".updatepreviewresponse",
    "UpdatePreviewResponseTypedDict": ".updatepreviewresponse",
    "UpdateSegmentRequestRequest": ".updatesegmentop",
    "UpdateSegmentRequestRequestTypedDict": ".updatesegmentop",
    "UpdateSegmentRequest": ".updatesegmentrequest",
    "UpdateSegmentRequestTypedDict": ".updatesegmentrequest",
    "UpdateTemplateRequestRequest": ".updatetemplateop",
    "UpdateTemplateRequestRequestTypedDict": ".updatetemplateop",
    "UpdateTemplatePreviewRequest": ".updatetemplatepreviewop",
    "UpdateTemplatePreviewRequestTypedDict": ".updatetemplatepreviewop",
    "UpdateTemplateRequest": ".updatetemplaterequest",
    "UpdateTemplateRequestTypedDict": ".updatetemplaterequest",
    "VerifyDomainRequest": ".verifydomainop",
    "VerifyDomainRequestTypedDict": ".verifydomainop",
    "Webhook": ".webhook",
    "WebhookTypedDict": ".webhook",
    "WebhookDelivery": ".webhookdelivery",
    "WebhookDeliveryTypedDict": ".webhookdelivery",
    "WebhookToggleResponse": ".webhooktoggleresponse",
    "WebhookToggleResponseTypedDict": ".webhooktoggleresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
