"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AddDomainRequestTypedDict(TypedDict):
    domain: str
    workspace_id: NotRequired[str]
    r"""Existing workspace to join as an alias; omit to create a workspace."""
    receiving_subdomain: NotRequired[str]


class AddDomainRequest(BaseModel):
    domain: str

    workspace_id: Optional[str] = None
    r"""Existing workspace to join as an alias; omit to create a workspace."""

    receiving_subdomain: Annotated[
        Optional[str], pydantic.Field(alias="receivingSubdomain")
    ] = "mail"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id", "receivingSubdomain"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AddDomainRequest.model_rebuild()
except NameError:
    pass
