"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AttachmentTypedDict(TypedDict):
    filename: str
    content: str
    r"""Base64 encoded file content"""
    content_type: NotRequired[str]


class Attachment(BaseModel):
    filename: str

    content: str
    r"""Base64 encoded file content"""

    content_type: Annotated[Optional[str], pydantic.Field(alias="contentType")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Attachment.model_rebuild()
except NameError:
    pass
