"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


AutomationWebhookProvider = Literal[
    "zapier",
    "n8n",
]


AutomationWebhookEventType = Literal["email.received",]


class AutomationWebhookTypedDict(TypedDict):
    id: str
    organization_id: str
    provider: AutomationWebhookProvider
    event_type: AutomationWebhookEventType
    target_url: str
    inbox_ids: Nullable[List[str]]
    active: bool
    created_at: datetime


class AutomationWebhook(BaseModel):
    id: str

    organization_id: str

    provider: AutomationWebhookProvider

    event_type: AutomationWebhookEventType

    target_url: str

    inbox_ids: Nullable[List[str]]

    active: bool

    created_at: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
