"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createcontactrequest import CreateContactRequest, CreateContactRequestTypedDict
from emailr.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class BulkCreateContactsRequestTypedDict(TypedDict):
    contacts: List[CreateContactRequestTypedDict]


class BulkCreateContactsRequest(BaseModel):
    contacts: List[CreateContactRequest]
