"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class BulkAddContactsToSegmentResponseTypedDict(TypedDict):
    added: int
    r"""Number of contacts successfully added to the segment"""
    already_in_segment: int
    r"""Number of contacts that were already in the segment"""
    not_found: int
    r"""Number of emails that were not found in the contacts list"""


class BulkAddContactsToSegmentResponse(BaseModel):
    added: int
    r"""Number of contacts successfully added to the segment"""

    already_in_segment: int
    r"""Number of contacts that were already in the segment"""

    not_found: int
    r"""Number of emails that were not found in the contacts list"""
