"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CheckEmailsResponseTypedDict(TypedDict):
    existing: List[str]
    r"""Emails that exist in the contact list"""
    missing: List[str]
    r"""Emails that do not exist in the contact list"""


class CheckEmailsResponse(BaseModel):
    existing: List[str]
    r"""Emails that exist in the contact list"""

    missing: List[str]
    r"""Emails that do not exist in the contact list"""
