"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ContactMetadataTypedDict = TypeAliasType(
    "ContactMetadataTypedDict", Union[str, float, bool]
)
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


ContactMetadata = TypeAliasType("ContactMetadata", Union[str, float, bool])
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


class ContactTypedDict(TypedDict):
    id: str
    organization_id: str
    email: str
    first_name: Nullable[str]
    last_name: Nullable[str]
    metadata: Nullable[Dict[str, ContactMetadataTypedDict]]
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""
    subscribed: bool
    unsubscribed_at: Nullable[datetime]
    tags: List[str]
    r"""Tags for categorization."""
    created_at: datetime
    updated_at: datetime
    workspace_id: NotRequired[Nullable[str]]
    r"""Owning domain workspace. Null only for archived legacy records."""


class Contact(BaseModel):
    id: str

    organization_id: str

    email: str

    first_name: Nullable[str]

    last_name: Nullable[str]

    metadata: Nullable[Dict[str, ContactMetadata]]
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""

    subscribed: bool

    unsubscribed_at: Nullable[datetime]

    tags: List[str]
    r"""Tags for categorization."""

    created_at: datetime

    updated_at: datetime

    workspace_id: OptionalNullable[str] = UNSET
    r"""Owning domain workspace. Null only for archived legacy records."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id"])
        nullable_fields = set(
            ["workspace_id", "first_name", "last_name", "metadata", "unsubscribed_at"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
