"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateBroadcastRequestTypedDict(TypedDict):
    name: str
    subject: str
    from_email: str
    template_id: NotRequired[str]
    segment_id: NotRequired[str]
    html_content: NotRequired[str]
    text_content: NotRequired[str]
    scheduled_at: NotRequired[datetime]


class CreateBroadcastRequest(BaseModel):
    name: str

    subject: str

    from_email: str

    template_id: Optional[str] = None

    segment_id: Optional[str] = None

    html_content: Optional[str] = None

    text_content: Optional[str] = None

    scheduled_at: Optional[datetime] = None
