"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateAPIKeyRequestTypedDict(TypedDict):
    name: str
    permissions: NotRequired[List[str]]


class CreateAPIKeyRequest(BaseModel):
    name: str

    permissions: Optional[List[str]] = None
