"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


CreateInvitationRequestRole = Literal[
    "member",
    "admin",
]
r"""Role to assign to the invited user"""


class CreateInvitationRequestTypedDict(TypedDict):
    email: str
    r"""Email address of the person to invite"""
    role: NotRequired[CreateInvitationRequestRole]


class CreateInvitationRequest(BaseModel):
    email: str
    r"""Email address of the person to invite"""

    role: Optional[CreateInvitationRequestRole] = "member"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
