"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


CreateWebhookRequestType = Literal[
    "transactional",
    "domain",
    "receiving",
]
r"""Webhook category type that determines which events the webhook subscribes to"""


class CreateWebhookRequestTypedDict(TypedDict):
    name: str
    url: str
    type: CreateWebhookRequestType
    r"""Webhook category type that determines which events the webhook subscribes to"""
    inbox_ids: NotRequired[List[str]]
    r"""Optional array of inbox UUIDs to scope receiving webhooks. Only applicable when type is 'receiving'."""


class CreateWebhookRequest(BaseModel):
    name: str

    url: str

    type: CreateWebhookRequestType
    r"""Webhook category type that determines which events the webhook subscribes to"""

    inbox_ids: Optional[List[str]] = None
    r"""Optional array of inbox UUIDs to scope receiving webhooks. Only applicable when type is 'receiving'."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["inbox_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
