"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filterconditions import FilterConditions, FilterConditionsTypedDict
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


CreateSegmentRequestType = Literal[
    "manual",
    "data_driven",
]
r"""Segment type: 'manual' for static segments, 'data_driven' for dynamic filter-based segments"""


class CreateSegmentRequestTypedDict(TypedDict):
    name: str
    description: NotRequired[str]
    type: NotRequired[CreateSegmentRequestType]
    conditions: NotRequired[FilterConditionsTypedDict]
    r"""Filter conditions for data-driven segments. Required when type is 'data_driven'."""


class CreateSegmentRequest(BaseModel):
    name: str

    description: Optional[str] = None

    type: Optional[CreateSegmentRequestType] = "manual"

    conditions: Optional[FilterConditions] = None
    r"""Filter conditions for data-driven segments. Required when type is 'data_driven'."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "type", "conditions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
