"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


CreateContactRequestMetadataTypedDict = TypeAliasType(
    "CreateContactRequestMetadataTypedDict", Union[str, float, bool]
)
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


CreateContactRequestMetadata = TypeAliasType(
    "CreateContactRequestMetadata", Union[str, float, bool]
)
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


class CreateContactRequestTypedDict(TypedDict):
    email: str
    first_name: NotRequired[Nullable[str]]
    last_name: NotRequired[Nullable[str]]
    subscribed: NotRequired[bool]
    metadata: NotRequired[Dict[str, CreateContactRequestMetadataTypedDict]]
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""
    tags: NotRequired[List[str]]
    r"""Tags for categorization. Lowercase, max 50 chars each, max 20 tags."""


class CreateContactRequest(BaseModel):
    email: str

    first_name: OptionalNullable[str] = UNSET

    last_name: OptionalNullable[str] = UNSET

    subscribed: Optional[bool] = True

    metadata: Optional[Dict[str, CreateContactRequestMetadata]] = None
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""

    tags: Optional[List[str]] = None
    r"""Tags for categorization. Lowercase, max 50 chars each, max 20 tags."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["first_name", "last_name", "subscribed", "metadata", "tags"]
        )
        nullable_fields = set(["first_name", "last_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
