"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateInboxRequestTypedDict(TypedDict):
    name: str
    username: str
    domain: str
    reply_to: NotRequired[str]
    r"""Custom reply-to address. Defaults to username@mail.domain if not provided."""
    signature_html: NotRequired[str]
    r"""HTML signature content appended to outgoing transactional emails"""
    signature_enabled: NotRequired[bool]
    r"""Whether to append the signature to outgoing transactional emails. Defaults to false."""
    slack_connection_id: NotRequired[str]
    r"""Slack OAuth connection ID for notifications"""
    slack_channel_id: NotRequired[str]
    r"""Slack channel ID to send notifications to"""
    slack_channel_name: NotRequired[str]
    r"""Slack channel display name (cached)"""
    slack_notifications_enabled: NotRequired[bool]
    r"""Whether to send Slack notifications for incoming emails"""


class CreateInboxRequest(BaseModel):
    name: str

    username: str

    domain: str

    reply_to: Optional[str] = None
    r"""Custom reply-to address. Defaults to username@mail.domain if not provided."""

    signature_html: Optional[str] = None
    r"""HTML signature content appended to outgoing transactional emails"""

    signature_enabled: Optional[bool] = None
    r"""Whether to append the signature to outgoing transactional emails. Defaults to false."""

    slack_connection_id: Optional[str] = None
    r"""Slack OAuth connection ID for notifications"""

    slack_channel_id: Optional[str] = None
    r"""Slack channel ID to send notifications to"""

    slack_channel_name: Optional[str] = None
    r"""Slack channel display name (cached)"""

    slack_notifications_enabled: Optional[bool] = None
    r"""Whether to send Slack notifications for incoming emails"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "reply_to",
                "signature_html",
                "signature_enabled",
                "slack_connection_id",
                "slack_channel_id",
                "slack_channel_name",
                "slack_notifications_enabled",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
