"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreateContactRequestTypedDict(TypedDict):
    email: str
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    subscribed: NotRequired[bool]
    metadata: NotRequired[Dict[str, Nullable[Any]]]


class CreateContactRequest(BaseModel):
    email: str

    first_name: Optional[str] = None

    last_name: Optional[str] = None

    subscribed: Optional[bool] = True

    metadata: Optional[Dict[str, Nullable[Any]]] = None
