"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateTemplateRequestTypedDict(TypedDict):
    name: str
    subject: str
    html_content: NotRequired[str]
    text_content: NotRequired[str]
    variables: NotRequired[List[str]]


class CreateTemplateRequest(BaseModel):
    name: str

    subject: str

    html_content: Optional[str] = None

    text_content: Optional[str] = None

    variables: Optional[List[str]] = None
