"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateSequenceStepRequestTypedDict(TypedDict):
    delay_hours: int
    r"""Hours to wait before sending this step."""
    step_number: NotRequired[int]
    r"""Position in the sequence. If omitted, appended to the end."""
    subject: NotRequired[Nullable[str]]
    html_content: NotRequired[Nullable[str]]
    text_content: NotRequired[Nullable[str]]
    template_id: NotRequired[Nullable[str]]


class CreateSequenceStepRequest(BaseModel):
    delay_hours: int
    r"""Hours to wait before sending this step."""

    step_number: Optional[int] = None
    r"""Position in the sequence. If omitted, appended to the end."""

    subject: OptionalNullable[str] = UNSET

    html_content: OptionalNullable[str] = UNSET

    text_content: OptionalNullable[str] = UNSET

    template_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["step_number", "subject", "html_content", "text_content", "template_id"]
        )
        nullable_fields = set(
            ["subject", "html_content", "text_content", "template_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
