"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


CreateContactRequestMetadataTypedDict = TypeAliasType(
    "CreateContactRequestMetadataTypedDict", Union[str, float, bool]
)
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


CreateContactRequestMetadata = TypeAliasType(
    "CreateContactRequestMetadata", Union[str, float, bool]
)
r"""Property value supporting string, number, boolean, or date (as ISO string) types"""


class CreateContactRequestTypedDict(TypedDict):
    email: str
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    subscribed: NotRequired[bool]
    metadata: NotRequired[Dict[str, Nullable[CreateContactRequestMetadataTypedDict]]]
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""


class CreateContactRequest(BaseModel):
    email: str

    first_name: Optional[str] = None

    last_name: Optional[str] = None

    subscribed: Optional[bool] = True

    metadata: Optional[Dict[str, Nullable[CreateContactRequestMetadata]]] = None
    r"""Custom properties for the contact. Supports string, number, boolean, and date (as ISO string) values."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["first_name", "last_name", "subscribed", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
