"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreateSegmentRequestTypedDict(TypedDict):
    name: str
    conditions: Dict[str, Nullable[Any]]
    description: NotRequired[str]


class CreateSegmentRequest(BaseModel):
    name: str

    conditions: Dict[str, Nullable[Any]]

    description: Optional[str] = None
