"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


CreatePropertyDefinitionRequestType = Literal[
    "string",
    "number",
    "boolean",
    "date",
]


class CreatePropertyDefinitionRequestTypedDict(TypedDict):
    name: str
    type: CreatePropertyDefinitionRequestType


class CreatePropertyDefinitionRequest(BaseModel):
    name: str

    type: CreatePropertyDefinitionRequestType
