"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable
from typing import Dict, List
from typing_extensions import TypedDict


class CSVImportPreviewResponseTypedDict(TypedDict):
    headers: List[str]
    r"""Column headers extracted from the CSV file"""
    preview_rows: List[Dict[str, str]]
    r"""First 5 rows of data as objects with header keys"""
    total_rows: int
    r"""Total number of data rows in the CSV (excluding header)"""
    suggested_mappings: Dict[str, Nullable[str]]
    r"""Auto-suggested mappings for column headers to contact properties. Value is null if no suggestion."""


class CSVImportPreviewResponse(BaseModel):
    headers: List[str]
    r"""Column headers extracted from the CSV file"""

    preview_rows: List[Dict[str, str]]
    r"""First 5 rows of data as objects with header keys"""

    total_rows: int
    r"""Total number of data rows in the CSV (excluding header)"""

    suggested_mappings: Dict[str, Nullable[str]]
    r"""Auto-suggested mappings for column headers to contact properties. Value is null if no suggestion."""
