"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .importerror import ImportErrorT, ImportErrorTTypedDict
from emailr.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CSVImportResponseTypedDict(TypedDict):
    created: int
    r"""Number of new contacts created"""
    updated: int
    r"""Number of existing contacts updated"""
    skipped: int
    r"""Number of rows skipped (invalid data or handle_missing='skip')"""
    errors: List[ImportErrorTTypedDict]
    r"""List of errors encountered during import"""


class CSVImportResponse(BaseModel):
    created: int
    r"""Number of new contacts created"""

    updated: int
    r"""Number of existing contacts updated"""

    skipped: int
    r"""Number of rows skipped (invalid data or handle_missing='skip')"""

    errors: List[ImportErrorT]
    r"""List of errors encountered during import"""
