"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteForwardingRuleRequestTypedDict(TypedDict):
    id: str


class DeleteForwardingRuleRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteForwardingRuleResponseTypedDict(TypedDict):
    r"""Forwarding rule deleted"""

    success: bool


class DeleteForwardingRuleResponse(BaseModel):
    r"""Forwarding rule deleted"""

    success: bool
