"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteV1ContactSyncIDRequestTypedDict(TypedDict):
    id: str


class DeleteV1ContactSyncIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteV1ContactSyncIDResponseTypedDict(TypedDict):
    r"""Sync deleted"""

    success: bool


class DeleteV1ContactSyncIDResponse(BaseModel):
    r"""Sync deleted"""

    success: bool
