"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteEmailCommentRequestTypedDict(TypedDict):
    email_id: str
    comment_id: str


class DeleteEmailCommentRequest(BaseModel):
    email_id: Annotated[
        str,
        pydantic.Field(alias="emailId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    comment_id: Annotated[
        str,
        pydantic.Field(alias="commentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class DeleteEmailCommentResponseTypedDict(TypedDict):
    r"""Comment deleted"""

    success: bool


class DeleteEmailCommentResponse(BaseModel):
    r"""Comment deleted"""

    success: bool
