"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteBroadcastRequestTypedDict(TypedDict):
    id: str


class DeleteBroadcastRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteBroadcastResponseTypedDict(TypedDict):
    r"""Broadcast deleted"""

    success: bool


class DeleteBroadcastResponse(BaseModel):
    r"""Broadcast deleted"""

    success: bool
