"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


Type = Literal[
    "TXT",
    "MX",
    "CNAME",
]


class DNSRecordTypedDict(TypedDict):
    type: Type
    name: str
    value: str
    priority: NotRequired[float]


class DNSRecord(BaseModel):
    type: Type

    name: str

    value: str

    priority: Optional[float] = None
