"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DomainVerificationStatusTypedDict(TypedDict):
    verified: bool
    status: str
    dkim_status: NotRequired[str]


class DomainVerificationStatus(BaseModel):
    verified: bool

    status: str

    dkim_status: Annotated[Optional[str], pydantic.Field(alias="dkimStatus")] = None
