"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DomainConnectSignResponseTypedDict(TypedDict):
    supported: bool
    url: NotRequired[str]
    r"""Signed Domain Connect apply URL"""
    url_sync_ux: NotRequired[str]
    r"""DNS provider's Domain Connect base URL"""
    error: NotRequired[str]
    r"""Error message when Domain Connect is not supported"""


class DomainConnectSignResponse(BaseModel):
    supported: bool

    url: Optional[str] = None
    r"""Signed Domain Connect apply URL"""

    url_sync_ux: Annotated[Optional[str], pydantic.Field(alias="urlSyncUX")] = None
    r"""DNS provider's Domain Connect base URL"""

    error: Optional[str] = None
    r"""Error message when Domain Connect is not supported"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["url", "urlSyncUX", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DomainConnectSignResponse.model_rebuild()
except NameError:
    pass
