"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dnsrecord import DNSRecord, DNSRecordTypedDict
from emailr.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class DomainDNSRecordsTypedDict(TypedDict):
    dkim: DNSRecordTypedDict
    spf: DNSRecordTypedDict
    dmarc: DNSRecordTypedDict
    mail_from_mx: DNSRecordTypedDict
    mail_from_spf: DNSRecordTypedDict
    receiving_mx: DNSRecordTypedDict


class DomainDNSRecords(BaseModel):
    dkim: DNSRecord

    spf: DNSRecord

    dmarc: DNSRecord

    mail_from_mx: Annotated[DNSRecord, pydantic.Field(alias="mailFromMx")]

    mail_from_spf: Annotated[DNSRecord, pydantic.Field(alias="mailFromSpf")]

    receiving_mx: Annotated[DNSRecord, pydantic.Field(alias="receivingMx")]


try:
    DomainDNSRecords.model_rebuild()
except NameError:
    pass
