"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .email import Email, EmailTypedDict
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class EmailEventTypedDict(TypedDict):
    id: str
    email_id: str
    event_type: str
    event_data: Nullable[Dict[str, Nullable[Any]]]
    ip_address: Nullable[str]
    user_agent: Nullable[str]
    created_at: datetime
    emails: NotRequired[EmailTypedDict]


class EmailEvent(BaseModel):
    id: str

    email_id: str

    event_type: str

    event_data: Nullable[Dict[str, Nullable[Any]]]

    ip_address: Nullable[str]

    user_agent: Nullable[str]

    created_at: datetime

    emails: Optional[Email] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["emails"]
        nullable_fields = ["event_data", "ip_address", "user_agent"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
