"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class EmailMetricsTypedDict(TypedDict):
    total: int
    sent: int
    delivered: int
    bounced: int
    complained: int


class EmailMetrics(BaseModel):
    total: int

    sent: int

    delivered: int

    bounced: int

    complained: int
