"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List
from typing_extensions import NotRequired, TypedDict


class EmailTypedDict(TypedDict):
    id: str
    organization_id: str
    message_id: str
    from_email: str
    to_email: str
    subject: Nullable[str]
    html_content: Nullable[str]
    text_content: Nullable[str]
    template_id: Nullable[str]
    status: str
    ses_message_id: Nullable[str]
    broadcast_id: Nullable[str]
    metadata: Nullable[Dict[str, Any]]
    sent_at: Nullable[datetime]
    delivered_at: Nullable[datetime]
    opened_at: Nullable[datetime]
    clicked_at: Nullable[datetime]
    bounced_at: Nullable[datetime]
    complained_at: Nullable[datetime]
    scheduled_at: Nullable[datetime]
    created_at: datetime
    thread_id: Nullable[str]
    parent_email_id: Nullable[str]
    attachments: Nullable[List[Any]]
    clicked_links: Nullable[List[Any]]
    opens: Nullable[List[Any]]
    workspace_id: NotRequired[Nullable[str]]
    r"""Owning domain workspace. Null only for archived legacy records."""


class Email(BaseModel):
    id: str

    organization_id: str

    message_id: str

    from_email: str

    to_email: str

    subject: Nullable[str]

    html_content: Nullable[str]

    text_content: Nullable[str]

    template_id: Nullable[str]

    status: str

    ses_message_id: Nullable[str]

    broadcast_id: Nullable[str]

    metadata: Nullable[Dict[str, Any]]

    sent_at: Nullable[datetime]

    delivered_at: Nullable[datetime]

    opened_at: Nullable[datetime]

    clicked_at: Nullable[datetime]

    bounced_at: Nullable[datetime]

    complained_at: Nullable[datetime]

    scheduled_at: Nullable[datetime]

    created_at: datetime

    thread_id: Nullable[str]

    parent_email_id: Nullable[str]

    attachments: Nullable[List[Any]]

    clicked_links: Nullable[List[Any]]

    opens: Nullable[List[Any]]

    workspace_id: OptionalNullable[str] = UNSET
    r"""Owning domain workspace. Null only for archived legacy records."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id"])
        nullable_fields = set(
            [
                "workspace_id",
                "subject",
                "html_content",
                "text_content",
                "template_id",
                "ses_message_id",
                "broadcast_id",
                "metadata",
                "sent_at",
                "delivered_at",
                "opened_at",
                "clicked_at",
                "bounced_at",
                "complained_at",
                "scheduled_at",
                "thread_id",
                "parent_email_id",
                "attachments",
                "clicked_links",
                "opens",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
