"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Literal, Optional
from typing_extensions import NotRequired, TypedDict


Operator = Literal[
    "exists",
    "not_exists",
    "equals",
    "not_equals",
    "greater_than",
    "less_than",
    "greater_than_or_equal",
    "less_than_or_equal",
    "contains",
    "not_contains",
    "starts_with",
    "ends_with",
]


class FilterRuleTypedDict(TypedDict):
    field: str
    operator: Operator
    value: NotRequired[Any]


class FilterRule(BaseModel):
    field: str

    operator: Operator

    value: Optional[Any] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
