"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ForwardEmailToTypedDict = TypeAliasType(
    "ForwardEmailToTypedDict", Union[str, List[str]]
)


ForwardEmailTo = TypeAliasType("ForwardEmailTo", Union[str, List[str]])


class ForwardEmailRequestTypedDict(TypedDict):
    email_id: str
    to: ForwardEmailToTypedDict
    message: NotRequired[str]


class ForwardEmailRequest(BaseModel):
    email_id: str

    to: ForwardEmailTo

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
