"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, List, Literal
from typing_extensions import NotRequired, TypedDict


GetV1ContactSyncSourceType = Literal[
    "supabase",
    "vercel",
    "webhook",
]


class SyncTypedDict(TypedDict):
    id: str
    organization_id: str
    source_type: GetV1ContactSyncSourceType
    source_project_id: str
    source_table: str
    sync_enabled: bool
    created_at: str
    field_mappings: NotRequired[Nullable[Any]]


class Sync(BaseModel):
    id: str

    organization_id: str

    source_type: GetV1ContactSyncSourceType

    source_project_id: str

    source_table: str

    sync_enabled: bool

    created_at: str

    field_mappings: OptionalNullable[Any] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["field_mappings"]
        nullable_fields = ["field_mappings"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class GetV1ContactSyncResponseTypedDict(TypedDict):
    r"""List of contact syncs"""

    syncs: List[SyncTypedDict]


class GetV1ContactSyncResponse(BaseModel):
    r"""List of contact syncs"""

    syncs: List[Sync]
