"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class GetContactLimitResponseTypedDict(TypedDict):
    r"""Contact limit information"""

    contact_limit: Nullable[float]
    current_count: float
    remaining_slots: Nullable[float]


class GetContactLimitResponse(BaseModel):
    r"""Contact limit information"""

    contact_limit: Annotated[Nullable[float], pydantic.Field(alias="contactLimit")]

    current_count: Annotated[float, pydantic.Field(alias="currentCount")]

    remaining_slots: Annotated[Nullable[float], pydantic.Field(alias="remainingSlots")]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    GetContactLimitResponse.model_rebuild()
except NameError:
    pass
