"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCurrentWorkspaceResponseTypedDict(TypedDict):
    r"""Current domain workspace"""

    user_id: str
    organization_id: str
    role: str
    domain: Nullable[str]
    account_role: NotRequired[str]
    workspace_id: NotRequired[Nullable[str]]


class GetCurrentWorkspaceResponse(BaseModel):
    r"""Current domain workspace"""

    user_id: Annotated[str, pydantic.Field(alias="userId")]

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]

    role: str

    domain: Nullable[str]

    account_role: Annotated[Optional[str], pydantic.Field(alias="accountRole")] = None

    workspace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="workspaceId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accountRole", "workspaceId"])
        nullable_fields = set(["workspaceId", "domain"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GetCurrentWorkspaceResponse.model_rebuild()
except NameError:
    pass
