"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetTemplatePreviewRequestTypedDict(TypedDict):
    template_id: str


class GetTemplatePreviewRequest(BaseModel):
    template_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
