"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetThreadDraftRequestTypedDict(TypedDict):
    thread_id: str


class GetThreadDraftRequest(BaseModel):
    thread_id: Annotated[
        str,
        pydantic.Field(alias="threadId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
