"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class InboxTypedDict(TypedDict):
    id: str
    organization_id: str
    name: str
    username: str
    domain: str
    reply_to: str
    r"""Reply-to address for outbound emails. Defaults to username@mail.domain when not set."""
    from_address: str
    r"""Computed from address (username@domain) used for outbound sending"""
    inbound_address: str
    r"""Computed inbound address (username@mail.domain) used for receiving emails"""
    signature_html: Nullable[str]
    r"""HTML signature content appended to outgoing transactional emails"""
    signature_enabled: bool
    r"""Whether to append the signature to outgoing transactional emails"""
    slack_connection_id: Nullable[str]
    r"""Slack OAuth connection ID for notifications"""
    slack_channel_id: Nullable[str]
    r"""Slack channel ID where notifications are sent"""
    slack_channel_name: Nullable[str]
    r"""Slack channel display name"""
    slack_notifications_enabled: bool
    r"""Whether Slack notifications are enabled for this inbox"""
    unread_thread_count: int
    r"""Number of unread threads in this inbox"""
    created_at: datetime
    updated_at: datetime


class Inbox(BaseModel):
    id: str

    organization_id: str

    name: str

    username: str

    domain: str

    reply_to: str
    r"""Reply-to address for outbound emails. Defaults to username@mail.domain when not set."""

    from_address: str
    r"""Computed from address (username@domain) used for outbound sending"""

    inbound_address: str
    r"""Computed inbound address (username@mail.domain) used for receiving emails"""

    signature_html: Nullable[str]
    r"""HTML signature content appended to outgoing transactional emails"""

    signature_enabled: bool
    r"""Whether to append the signature to outgoing transactional emails"""

    slack_connection_id: Nullable[str]
    r"""Slack OAuth connection ID for notifications"""

    slack_channel_id: Nullable[str]
    r"""Slack channel ID where notifications are sent"""

    slack_channel_name: Nullable[str]
    r"""Slack channel display name"""

    slack_notifications_enabled: bool
    r"""Whether Slack notifications are enabled for this inbox"""

    unread_thread_count: int
    r"""Number of unread threads in this inbox"""

    created_at: datetime

    updated_at: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
