"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import TypedDict


InvitationDetailsRole = Literal[
    "member",
    "admin",
]
r"""Role being offered"""


class InvitationDetailsTypedDict(TypedDict):
    organization_name: str
    r"""Name of the organization"""
    inviter_name: Nullable[str]
    r"""Full name of the person who sent the invitation"""
    inviter_email: str
    r"""Email of the person who sent the invitation"""
    role: InvitationDetailsRole
    email: str
    r"""Email address the invitation was sent to"""
    is_expired: bool
    r"""Whether the invitation has expired"""
    expires_at: datetime
    r"""When the invitation expires"""


class InvitationDetails(BaseModel):
    organization_name: str
    r"""Name of the organization"""

    inviter_name: Nullable[str]
    r"""Full name of the person who sent the invitation"""

    inviter_email: str
    r"""Email of the person who sent the invitation"""

    role: InvitationDetailsRole

    email: str
    r"""Email address the invitation was sent to"""

    is_expired: bool
    r"""Whether the invitation has expired"""

    expires_at: datetime
    r"""When the invitation expires"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
