"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


InvitationStatus = Literal[
    "pending",
    "accepted",
    "expired",
    "cancelled",
]
