"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DataTypedDict(TypedDict):
    id: str
    name: str
    from_pattern: str
    to_addresses: List[str]
    active: bool
    created_at: str


class Data(BaseModel):
    id: str

    name: str

    from_pattern: str

    to_addresses: List[str]

    active: bool

    created_at: str


class ListForwardingRulesResponseTypedDict(TypedDict):
    r"""List of forwarding rules"""

    data: List[DataTypedDict]


class ListForwardingRulesResponse(BaseModel):
    r"""List of forwarding rules"""

    data: List[Data]
