"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class MarkThreadReadRequestTypedDict(TypedDict):
    thread_id: str


class MarkThreadReadRequest(BaseModel):
    thread_id: Annotated[
        str,
        pydantic.Field(alias="threadId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class MarkThreadReadResponseTypedDict(TypedDict):
    r"""Thread marked as read"""

    success: bool
    updated: float


class MarkThreadReadResponse(BaseModel):
    r"""Thread marked as read"""

    success: bool

    updated: float
