"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class OrganizationTypedDict(TypedDict):
    id: str
    name: str
    slug: str
    plan: Nullable[str]
    billing_email: Nullable[str]
    stripe_customer_id: Nullable[str]
    stripe_subscription_id: Nullable[str]
    usage_limit: Nullable[float]
    created_at: datetime
    updated_at: datetime
    ses_configuration_set: Nullable[str]
    ses_tenant_name: Nullable[str]
    ses_tenant_id: Nullable[str]


class Organization(BaseModel):
    id: str

    name: str

    slug: str

    plan: Nullable[str]

    billing_email: Nullable[str]

    stripe_customer_id: Nullable[str]

    stripe_subscription_id: Nullable[str]

    usage_limit: Nullable[float]

    created_at: datetime

    updated_at: datetime

    ses_configuration_set: Nullable[str]

    ses_tenant_name: Nullable[str]

    ses_tenant_id: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = [
            "plan",
            "billing_email",
            "stripe_customer_id",
            "stripe_subscription_id",
            "usage_limit",
            "ses_configuration_set",
            "ses_tenant_name",
            "ses_tenant_id",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
