"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


PlanType = Literal[
    "transactional",
    "marketing",
]


class PostV1BillingCheckoutRequestTypedDict(TypedDict):
    price_id: str
    r"""Stripe Price ID"""
    plan_type: PlanType


class PostV1BillingCheckoutRequest(BaseModel):
    price_id: Annotated[str, pydantic.Field(alias="priceId")]
    r"""Stripe Price ID"""

    plan_type: Annotated[PlanType, pydantic.Field(alias="planType")]


class PostV1BillingCheckoutResponseTypedDict(TypedDict):
    r"""Checkout session created"""

    session_id: str
    url: str


class PostV1BillingCheckoutResponse(BaseModel):
    r"""Checkout session created"""

    session_id: Annotated[str, pydantic.Field(alias="sessionId")]

    url: str
