"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from emailr.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PutV1TopicsIDRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]


class PutV1TopicsIDRequestBody(BaseModel):
    name: Optional[str] = None

    description: Optional[str] = None


class PutV1TopicsIDRequestTypedDict(TypedDict):
    id: str
    body: NotRequired[PutV1TopicsIDRequestBodyTypedDict]


class PutV1TopicsIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        Optional[PutV1TopicsIDRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class PutV1TopicsIDResponseTypedDict(TypedDict):
    r"""Topic updated"""

    id: str
    organization_id: str
    name: str
    description: Nullable[str]
    created_at: str
    updated_at: str


class PutV1TopicsIDResponse(BaseModel):
    r"""Topic updated"""

    id: str

    organization_id: str

    name: str

    description: Nullable[str]

    created_at: str

    updated_at: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
