"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ReplyToTypedDict(TypedDict):
    in_reply_to: NotRequired[str]
    thread_id: NotRequired[str]
    parent_email_id: NotRequired[str]


class ReplyTo(BaseModel):
    in_reply_to: Optional[str] = None

    thread_id: Optional[str] = None

    parent_email_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["in_reply_to", "thread_id", "parent_email_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
