"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class SendEmailResponseTypedDict(TypedDict):
    success: bool
    message_id: str
    recipients: int


class SendEmailResponse(BaseModel):
    success: bool

    message_id: str

    recipients: int
