"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class SendBroadcastResponseTypedDict(TypedDict):
    success: bool
    sent: int
    total: int


class SendBroadcastResponse(BaseModel):
    success: bool

    sent: int

    total: int
