"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SequenceStepTypedDict(TypedDict):
    id: str
    broadcast_id: str
    step_number: int
    r"""Position of this step in the sequence (1-indexed)."""
    delay_hours: int
    r"""Hours to wait before sending this step (after the previous step or initial send)."""
    subject: Nullable[str]
    r"""Optional subject override. When null, the follow-up uses 'Re: <original subject>' so it threads as a reply."""
    html_content: Nullable[str]
    text_content: Nullable[str]
    template_id: Nullable[str]
    created_at: datetime
    updated_at: datetime
    workspace_id: NotRequired[Nullable[str]]
    r"""Owning domain workspace. Null only for archived legacy records."""


class SequenceStep(BaseModel):
    id: str

    broadcast_id: str

    step_number: int
    r"""Position of this step in the sequence (1-indexed)."""

    delay_hours: int
    r"""Hours to wait before sending this step (after the previous step or initial send)."""

    subject: Nullable[str]
    r"""Optional subject override. When null, the follow-up uses 'Re: <original subject>' so it threads as a reply."""

    html_content: Nullable[str]

    text_content: Nullable[str]

    template_id: Nullable[str]

    created_at: datetime

    updated_at: datetime

    workspace_id: OptionalNullable[str] = UNSET
    r"""Owning domain workspace. Null only for archived legacy records."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id"])
        nullable_fields = set(
            ["workspace_id", "subject", "html_content", "text_content", "template_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
