"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class PortsTypedDict(TypedDict):
    tls: float
    ssl: float
    tls_alternative: float


class Ports(BaseModel):
    tls: float

    ssl: float

    tls_alternative: float


class SMTPCredentialsTypedDict(TypedDict):
    server: str
    ports: PortsTypedDict
    username: str
    password: str
    encryption: str
    note: str


class SMTPCredentials(BaseModel):
    server: str

    ports: Ports

    username: str

    password: str

    encryption: str

    note: str
