"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


SubscribeAutomationWebhookRequestEventType = Literal["email.received",]


SubscribeAutomationWebhookRequestProvider = Literal[
    "zapier",
    "n8n",
]


class SubscribeAutomationWebhookRequestTypedDict(TypedDict):
    target_url: str
    event_type: SubscribeAutomationWebhookRequestEventType
    provider: SubscribeAutomationWebhookRequestProvider
    inbox_ids: NotRequired[List[str]]
    r"""Optional array of inbox UUIDs to scope the trigger."""
    send_test: NotRequired[bool]
    r"""Deprecated and ignored on subscribe. Use the dedicated automation-webhooks test endpoint to send a sample event."""


class SubscribeAutomationWebhookRequest(BaseModel):
    target_url: str

    event_type: SubscribeAutomationWebhookRequestEventType

    provider: SubscribeAutomationWebhookRequestProvider

    inbox_ids: Optional[List[str]] = None
    r"""Optional array of inbox UUIDs to scope the trigger."""

    send_test: Optional[bool] = None
    r"""Deprecated and ignored on subscribe. Use the dedicated automation-webhooks test endpoint to send a sample event."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["inbox_ids", "send_test"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
