"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class TemplateTypedDict(TypedDict):
    id: str
    organization_id: str
    name: str
    subject: str
    html_content: Nullable[str]
    text_content: Nullable[str]
    variables: Nullable[List[str]]
    from_email: Nullable[str]
    reply_to: Nullable[str]
    preview_text: Nullable[str]
    preview_html: Nullable[str]
    r"""Preview HTML content for AI agent review workflow"""
    created_by: Nullable[str]
    created_at: datetime
    updated_at: datetime


class Template(BaseModel):
    id: str

    organization_id: str

    name: str

    subject: str

    html_content: Nullable[str]

    text_content: Nullable[str]

    variables: Nullable[List[str]]

    from_email: Nullable[str]

    reply_to: Nullable[str]

    preview_text: Nullable[str]

    preview_html: Nullable[str]
    r"""Preview HTML content for AI agent review workflow"""

    created_by: Nullable[str]

    created_at: datetime

    updated_at: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
