"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class TestAutomationWebhookRequestTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    target_url: str


class TestAutomationWebhookRequest(BaseModel):
    __test__ = False

    target_url: str
