"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, List
from typing_extensions import TypedDict


class MessageTypedDict(TypedDict):
    id: str
    from_email: str
    to_email: str
    cc_emails: Nullable[List[str]]
    bcc_emails: Nullable[List[str]]
    subject: Nullable[str]
    html_content: Nullable[str]
    text_content: Nullable[str]
    status: str
    labels: List[str]
    attachments: Nullable[List[Any]]
    created_at: str
    sent_at: Nullable[str]


class Message(BaseModel):
    id: str

    from_email: str

    to_email: str

    cc_emails: Nullable[List[str]]

    bcc_emails: Nullable[List[str]]

    subject: Nullable[str]

    html_content: Nullable[str]

    text_content: Nullable[str]

    status: str

    labels: List[str]

    attachments: Nullable[List[Any]]

    created_at: str

    sent_at: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ThreadDetailTypedDict(TypedDict):
    thread_id: str
    subject: Nullable[str]
    labels: List[str]
    messages: List[MessageTypedDict]


class ThreadDetail(BaseModel):
    thread_id: str

    subject: Nullable[str]

    labels: List[str]

    messages: List[Message]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
