"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class ThreadDraftTypedDict(TypedDict):
    id: str
    thread_id: str
    html_content: Nullable[str]
    text_content: Nullable[str]
    to_email: Nullable[str]
    cc_emails: Nullable[List[str]]
    bcc_emails: Nullable[List[str]]
    from_email: Nullable[str]
    subject: Nullable[str]
    created_at: str
    updated_at: str


class ThreadDraft(BaseModel):
    id: str

    thread_id: str

    html_content: Nullable[str]

    text_content: Nullable[str]

    to_email: Nullable[str]

    cc_emails: Nullable[List[str]]

    bcc_emails: Nullable[List[str]]

    from_email: Nullable[str]

    subject: Nullable[str]

    created_at: str

    updated_at: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
