"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UnsubscribeSettingsTypedDict(TypedDict):
    id: NotRequired[str]
    organization_id: NotRequired[str]
    custom_message: NotRequired[Nullable[str]]
    redirect_url: NotRequired[Nullable[str]]
    one_click_enabled: NotRequired[Nullable[bool]]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class UnsubscribeSettings(BaseModel):
    id: Optional[str] = None

    organization_id: Optional[str] = None

    custom_message: OptionalNullable[str] = UNSET

    redirect_url: OptionalNullable[str] = UNSET

    one_click_enabled: OptionalNullable[bool] = UNSET

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "id",
            "organization_id",
            "custom_message",
            "redirect_url",
            "one_click_enabled",
            "created_at",
            "updated_at",
        ]
        nullable_fields = ["custom_message", "redirect_url", "one_click_enabled"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
