"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UpdateTemplateRequestTypedDict(TypedDict):
    name: NotRequired[str]
    subject: NotRequired[str]
    html_content: NotRequired[str]
    text_content: NotRequired[str]
    variables: NotRequired[List[str]]
    from_email: NotRequired[str]
    r"""Default from email address. Must match a verified domain."""
    reply_to: NotRequired[str]
    r"""Reply-To email address for template-based emails."""
    preview_text: NotRequired[str]
    r"""Preview text (preheader) shown in email clients."""


class UpdateTemplateRequest(BaseModel):
    name: Optional[str] = None

    subject: Optional[str] = None

    html_content: Optional[str] = None

    text_content: Optional[str] = None

    variables: Optional[List[str]] = None

    from_email: Optional[str] = None
    r"""Default from email address. Must match a verified domain."""

    reply_to: Optional[str] = None
    r"""Reply-To email address for template-based emails."""

    preview_text: Optional[str] = None
    r"""Preview text (preheader) shown in email clients."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "subject",
                "html_content",
                "text_content",
                "variables",
                "from_email",
                "reply_to",
                "preview_text",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
