"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createtemplaterequest import CreateTemplateRequest, CreateTemplateRequestTypedDict
from emailr.types import BaseModel
from emailr.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateTemplateRequestTypedDict(TypedDict):
    id: str
    body: NotRequired[CreateTemplateRequestTypedDict]


class UpdateTemplateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body: Annotated[
        Optional[CreateTemplateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
