"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateInboxRequestTypedDict(TypedDict):
    name: NotRequired[str]
    reply_to: NotRequired[Nullable[str]]
    r"""Custom reply-to address. Set to null to reset to default (username@mail.domain)."""
    signature_html: NotRequired[Nullable[str]]
    r"""HTML signature content appended to outgoing transactional emails"""
    signature_enabled: NotRequired[bool]
    r"""Whether to append the signature to outgoing transactional emails"""
    slack_connection_id: NotRequired[Nullable[str]]
    r"""Slack OAuth connection ID for notifications. Set to null to disconnect."""
    slack_channel_id: NotRequired[Nullable[str]]
    r"""Slack channel ID to send notifications to"""
    slack_channel_name: NotRequired[Nullable[str]]
    r"""Slack channel display name (cached)"""
    slack_notifications_enabled: NotRequired[bool]
    r"""Whether to send Slack notifications for incoming emails"""


class UpdateInboxRequest(BaseModel):
    name: Optional[str] = None

    reply_to: OptionalNullable[str] = UNSET
    r"""Custom reply-to address. Set to null to reset to default (username@mail.domain)."""

    signature_html: OptionalNullable[str] = UNSET
    r"""HTML signature content appended to outgoing transactional emails"""

    signature_enabled: Optional[bool] = None
    r"""Whether to append the signature to outgoing transactional emails"""

    slack_connection_id: OptionalNullable[str] = UNSET
    r"""Slack OAuth connection ID for notifications. Set to null to disconnect."""

    slack_channel_id: OptionalNullable[str] = UNSET
    r"""Slack channel ID to send notifications to"""

    slack_channel_name: OptionalNullable[str] = UNSET
    r"""Slack channel display name (cached)"""

    slack_notifications_enabled: Optional[bool] = None
    r"""Whether to send Slack notifications for incoming emails"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "reply_to",
                "signature_html",
                "signature_enabled",
                "slack_connection_id",
                "slack_channel_id",
                "slack_channel_name",
                "slack_notifications_enabled",
            ]
        )
        nullable_fields = set(
            [
                "reply_to",
                "signature_html",
                "slack_connection_id",
                "slack_channel_id",
                "slack_channel_name",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
