"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatelabelsrequest import UpdateLabelsRequest, UpdateLabelsRequestTypedDict
from emailr.types import BaseModel, UNSET_SENTINEL
from emailr.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateEmailLabelsRequestTypedDict(TypedDict):
    email_id: str
    body: NotRequired[UpdateLabelsRequestTypedDict]


class UpdateEmailLabelsRequest(BaseModel):
    email_id: Annotated[
        str,
        pydantic.Field(alias="emailId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        Optional[UpdateLabelsRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateEmailLabelsResponseTypedDict(TypedDict):
    r"""Labels updated"""

    success: bool
    labels: List[str]


class UpdateEmailLabelsResponse(BaseModel):
    r"""Labels updated"""

    success: bool

    labels: List[str]
