"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateDomainRequestTypedDict(TypedDict):
    receiving_enabled: NotRequired[bool]


class UpdateDomainRequest(BaseModel):
    receiving_enabled: Optional[bool] = None
