"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


UpdateBroadcastRequestSendingSpeed = Literal[
    "auto",
    "warmup",
    "very_slow",
    "slow",
    "normal",
    "instant",
]
r"""Controls how fast emails are sent."""


class SequenceExitConditionsTypedDict(TypedDict):
    r"""Configurable exit rules for the sequence dispatcher. Recipients matching any rule are removed from the sequence before the next follow-up."""

    exit_if_in_segment_ids: NotRequired[List[str]]
    exit_if_not_in_segment_ids: NotRequired[List[str]]


class SequenceExitConditions(BaseModel):
    r"""Configurable exit rules for the sequence dispatcher. Recipients matching any rule are removed from the sequence before the next follow-up."""

    exit_if_in_segment_ids: Optional[List[str]] = None

    exit_if_not_in_segment_ids: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["exit_if_in_segment_ids", "exit_if_not_in_segment_ids"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UpdateBroadcastRequestSequenceMode = Literal[
    "sales",
    "marketing",
]
r"""Product type and delivery behavior. sales = threaded replies; marketing = standalone campaign emails."""


class UpdateBroadcastRequestTypedDict(TypedDict):
    name: NotRequired[str]
    subject: NotRequired[str]
    from_email: NotRequired[str]
    from_name: NotRequired[str]
    reply_to: NotRequired[Nullable[str]]
    preview_text: NotRequired[Nullable[str]]
    template_id: NotRequired[Nullable[str]]
    segment_id: NotRequired[Nullable[str]]
    topic_id: NotRequired[Nullable[str]]
    scheduled_at: NotRequired[Nullable[datetime]]
    inbox_id: NotRequired[Nullable[str]]
    r"""Optional inbox ID. When provided, the inbox's name, from address, and reply-to address are used as defaults unless explicit values are given. Set to null to remove inbox association. Mutually exclusive with inbox_ids."""
    inbox_ids: NotRequired[Nullable[List[str]]]
    r"""Optional array of inbox IDs for inbox rotation. Each inbox's sender identity is used for its portion of emails. Set to null or empty to disable rotation. Mutually exclusive with inbox_id."""
    sending_speed: NotRequired[Nullable[UpdateBroadcastRequestSendingSpeed]]
    r"""Controls how fast emails are sent."""
    sequence_exit_conditions: NotRequired[Nullable[SequenceExitConditionsTypedDict]]
    r"""Configurable exit rules for the sequence dispatcher. Recipients matching any rule are removed from the sequence before the next follow-up."""
    sequence_mode: NotRequired[UpdateBroadcastRequestSequenceMode]
    r"""Product type and delivery behavior. sales = threaded replies; marketing = standalone campaign emails."""
    tags: NotRequired[List[str]]
    r"""Tags for categorization. Lowercase, max 50 chars each, max 20 tags."""


class UpdateBroadcastRequest(BaseModel):
    name: Optional[str] = None

    subject: Optional[str] = None

    from_email: Optional[str] = None

    from_name: Optional[str] = None

    reply_to: OptionalNullable[str] = UNSET

    preview_text: OptionalNullable[str] = UNSET

    template_id: OptionalNullable[str] = UNSET

    segment_id: OptionalNullable[str] = UNSET

    topic_id: OptionalNullable[str] = UNSET

    scheduled_at: OptionalNullable[datetime] = UNSET

    inbox_id: OptionalNullable[str] = UNSET
    r"""Optional inbox ID. When provided, the inbox's name, from address, and reply-to address are used as defaults unless explicit values are given. Set to null to remove inbox association. Mutually exclusive with inbox_ids."""

    inbox_ids: OptionalNullable[List[str]] = UNSET
    r"""Optional array of inbox IDs for inbox rotation. Each inbox's sender identity is used for its portion of emails. Set to null or empty to disable rotation. Mutually exclusive with inbox_id."""

    sending_speed: OptionalNullable[UpdateBroadcastRequestSendingSpeed] = UNSET
    r"""Controls how fast emails are sent."""

    sequence_exit_conditions: OptionalNullable[SequenceExitConditions] = UNSET
    r"""Configurable exit rules for the sequence dispatcher. Recipients matching any rule are removed from the sequence before the next follow-up."""

    sequence_mode: Optional[UpdateBroadcastRequestSequenceMode] = None
    r"""Product type and delivery behavior. sales = threaded replies; marketing = standalone campaign emails."""

    tags: Optional[List[str]] = None
    r"""Tags for categorization. Lowercase, max 50 chars each, max 20 tags."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "subject",
                "from_email",
                "from_name",
                "reply_to",
                "preview_text",
                "template_id",
                "segment_id",
                "topic_id",
                "scheduled_at",
                "inbox_id",
                "inbox_ids",
                "sending_speed",
                "sequence_exit_conditions",
                "sequence_mode",
                "tags",
            ]
        )
        nullable_fields = set(
            [
                "reply_to",
                "preview_text",
                "template_id",
                "segment_id",
                "topic_id",
                "scheduled_at",
                "inbox_id",
                "inbox_ids",
                "sending_speed",
                "sequence_exit_conditions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
