"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class WebhookDeliveryTypedDict(TypedDict):
    id: str
    webhook_id: str
    event_type: str
    payload: Dict[str, Any]
    response_status: Nullable[float]
    response_body: Nullable[str]
    attempt_count: float
    delivered_at: Nullable[datetime]
    created_at: datetime
    workspace_id: NotRequired[Nullable[str]]
    r"""Owning domain workspace. Null only for archived legacy records."""


class WebhookDelivery(BaseModel):
    id: str

    webhook_id: str

    event_type: str

    payload: Dict[str, Any]

    response_status: Nullable[float]

    response_body: Nullable[str]

    attempt_count: float

    delivered_at: Nullable[datetime]

    created_at: datetime

    workspace_id: OptionalNullable[str] = UNSET
    r"""Owning domain workspace. Null only for archived legacy records."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id"])
        nullable_fields = set(
            ["workspace_id", "response_status", "response_body", "delivered_at"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
