"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import NotRequired, TypedDict


WebhookType = Literal[
    "transactional",
    "domain",
    "receiving",
]
r"""Webhook category type that determines which events the webhook subscribes to"""


class WebhookTypedDict(TypedDict):
    id: str
    organization_id: str
    name: str
    url: str
    type: WebhookType
    r"""Webhook category type that determines which events the webhook subscribes to"""
    events: List[str]
    r"""Derived list of events based on the webhook type. Read-only."""
    inbox_ids: Nullable[List[str]]
    r"""Inbox UUIDs for scoping receiving webhooks. Null for non-receiving types."""
    secret: str
    active: bool
    created_by: Nullable[str]
    created_at: datetime
    workspace_id: NotRequired[Nullable[str]]
    r"""Owning domain workspace. Null only for archived legacy records."""


class Webhook(BaseModel):
    id: str

    organization_id: str

    name: str

    url: str

    type: WebhookType
    r"""Webhook category type that determines which events the webhook subscribes to"""

    events: List[str]
    r"""Derived list of events based on the webhook type. Read-only."""

    inbox_ids: Nullable[List[str]]
    r"""Inbox UUIDs for scoping receiving webhooks. Null for non-receiving types."""

    secret: str

    active: bool

    created_by: Nullable[str]

    created_at: datetime

    workspace_id: OptionalNullable[str] = UNSET
    r"""Owning domain workspace. Null only for archived legacy records."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspace_id"])
        nullable_fields = set(["workspace_id", "inbox_ids", "created_by"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
