"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from emailr.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


WebhookType = Literal[
    "transactional",
    "domain",
    "receiving",
]
r"""Webhook category type that determines which events the webhook subscribes to"""


class WebhookTypedDict(TypedDict):
    id: str
    organization_id: str
    name: str
    url: str
    type: WebhookType
    r"""Webhook category type that determines which events the webhook subscribes to"""
    events: List[str]
    r"""Derived list of events based on the webhook type. Read-only."""
    inbox_ids: Nullable[List[str]]
    r"""Inbox UUIDs for scoping receiving webhooks. Null for non-receiving types."""
    secret: str
    active: bool
    created_by: Nullable[str]
    created_at: datetime


class Webhook(BaseModel):
    id: str

    organization_id: str

    name: str

    url: str

    type: WebhookType
    r"""Webhook category type that determines which events the webhook subscribes to"""

    events: List[str]
    r"""Derived list of events based on the webhook type. Read-only."""

    inbox_ids: Nullable[List[str]]
    r"""Inbox UUIDs for scoping receiving webhooks. Null for non-receiving types."""

    secret: str

    active: bool

    created_by: Nullable[str]

    created_at: datetime

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
