"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from emailr.types import BaseModel
from typing_extensions import TypedDict


class WebhookToggleResponseTypedDict(TypedDict):
    success: bool
    active: bool


class WebhookToggleResponse(BaseModel):
    success: bool

    active: bool
