workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Emailr API:
        inputs:
            - location: https://api.emailr.dev/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/hormo/emailr/emailr-api
targets:
    emailr:
        target: python
        source: Emailr API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hormo/emailr/emailr-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
